/*
* vpc
* VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
*
* OpenAPI spec version: 2020-09-17T02:27:03Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vpc) {
      root.Vpc = {};
    }
    root.Vpc.CreateVpcRequest = factory(root.Vpc.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreateVpcRequest model module.
   * @module model/CreateVpcRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CreateVpcRequest</code>.
   * @alias module:model/CreateVpcRequest
   * @class
   * @param ipv4CidrBlock {String} IPv4 CIDR블록
   */
  var exports = function(ipv4CidrBlock) {
    var _this = this;


    _this['ipv4CidrBlock'] = ipv4CidrBlock;

  };

  /**
   * Constructs a <code>CreateVpcRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateVpcRequest} obj Optional instance to populate.
   * @return {module:model/CreateVpcRequest} The populated <code>CreateVpcRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('ipv4CidrBlock')) {
        obj['ipv4CidrBlock'] = ApiClient.convertToType(data['ipv4CidrBlock'], 'String');
      }
      if (data.hasOwnProperty('vpcName')) {
        obj['vpcName'] = ApiClient.convertToType(data['vpcName'], 'String');
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * IPv4 CIDR블록
   * @member {String} ipv4CidrBlock
   */
  exports.prototype['ipv4CidrBlock'] = undefined;
  /**
   * VPC이름
   * @member {String} vpcName
   */
  exports.prototype['vpcName'] = undefined;



  return exports;
}));


