/*
* vpc
* VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vpc) {
      root.Vpc = {};
    }
    root.Vpc.GetNatGatewayInstanceListRequest = factory(root.Vpc.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetNatGatewayInstanceListRequest model module.
   * @module model/GetNatGatewayInstanceListRequest
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>GetNatGatewayInstanceListRequest</code>.
   * @alias module:model/GetNatGatewayInstanceListRequest
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>GetNatGatewayInstanceListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetNatGatewayInstanceListRequest} obj Optional instance to populate.
   * @return {module:model/GetNatGatewayInstanceListRequest} The populated <code>GetNatGatewayInstanceListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('zoneCode')) {
        obj['zoneCode'] = ApiClient.convertToType(data['zoneCode'], 'String');
      }
      if (data.hasOwnProperty('natGatewayInstanceNoList')) {
        obj['natGatewayInstanceNoList'] = ApiClient.convertToType(data['natGatewayInstanceNoList'], ['String']);
      }
      if (data.hasOwnProperty('publicIp')) {
        obj['publicIp'] = ApiClient.convertToType(data['publicIp'], 'String');
      }
      if (data.hasOwnProperty('vpcName')) {
        obj['vpcName'] = ApiClient.convertToType(data['vpcName'], 'String');
      }
      if (data.hasOwnProperty('natGatewayName')) {
        obj['natGatewayName'] = ApiClient.convertToType(data['natGatewayName'], 'String');
      }
      if (data.hasOwnProperty('natGatewayInstanceStatusCode')) {
        obj['natGatewayInstanceStatusCode'] = ApiClient.convertToType(data['natGatewayInstanceStatusCode'], 'String');
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * ZONE코드
   * @member {String} zoneCode
   */
  exports.prototype['zoneCode'] = undefined;
  /**
   * NATGateway인스턴스번호리스트
   * @member {Array.<String>} natGatewayInstanceNoList
   */
  exports.prototype['natGatewayInstanceNoList'] = undefined;
  /**
   * 공인IP주소
   * @member {String} publicIp
   */
  exports.prototype['publicIp'] = undefined;
  /**
   * VPC이름
   * @member {String} vpcName
   */
  exports.prototype['vpcName'] = undefined;
  /**
   * natGatewayName
   * @member {String} natGatewayName
   */
  exports.prototype['natGatewayName'] = undefined;
  /**
   * NATGateway인스턴스상태코드
   * @member {String} natGatewayInstanceStatusCode
   */
  exports.prototype['natGatewayInstanceStatusCode'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;



  return exports;
}));


