/*
* vpc
* VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
*
* OpenAPI spec version: 2020-09-17T02:27:03Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vpc) {
      root.Vpc = {};
    }
    root.Vpc.GetNetworkAclListRequest = factory(root.Vpc.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetNetworkAclListRequest model module.
   * @module model/GetNetworkAclListRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetNetworkAclListRequest</code>.
   * @alias module:model/GetNetworkAclListRequest
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>GetNetworkAclListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetNetworkAclListRequest} obj Optional instance to populate.
   * @return {module:model/GetNetworkAclListRequest} The populated <code>GetNetworkAclListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('networkAclName')) {
        obj['networkAclName'] = ApiClient.convertToType(data['networkAclName'], 'String');
      }
      if (data.hasOwnProperty('networkAclStatusCode')) {
        obj['networkAclStatusCode'] = ApiClient.convertToType(data['networkAclStatusCode'], 'String');
      }
      if (data.hasOwnProperty('networkAclNoList')) {
        obj['networkAclNoList'] = ApiClient.convertToType(data['networkAclNoList'], ['String']);
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('vpcNo')) {
        obj['vpcNo'] = ApiClient.convertToType(data['vpcNo'], 'String');
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * 네트워크ACL이름
   * @member {String} networkAclName
   */
  exports.prototype['networkAclName'] = undefined;
  /**
   * 네트워크ACL상태코드
   * @member {String} networkAclStatusCode
   */
  exports.prototype['networkAclStatusCode'] = undefined;
  /**
   * 네트워크ACL번호리스트
   * @member {Array.<String>} networkAclNoList
   */
  exports.prototype['networkAclNoList'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * VPC번호
   * @member {String} vpcNo
   */
  exports.prototype['vpcNo'] = undefined;



  return exports;
}));


