/*
* vpc
* VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vpc) {
      root.Vpc = {};
    }
    root.Vpc.GetVpcPeeringInstanceListRequest = factory(root.Vpc.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetVpcPeeringInstanceListRequest model module.
   * @module model/GetVpcPeeringInstanceListRequest
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>GetVpcPeeringInstanceListRequest</code>.
   * @alias module:model/GetVpcPeeringInstanceListRequest
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>GetVpcPeeringInstanceListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetVpcPeeringInstanceListRequest} obj Optional instance to populate.
   * @return {module:model/GetVpcPeeringInstanceListRequest} The populated <code>GetVpcPeeringInstanceListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('vpcPeeringInstanceNoList')) {
        obj['vpcPeeringInstanceNoList'] = ApiClient.convertToType(data['vpcPeeringInstanceNoList'], ['String']);
      }
      if (data.hasOwnProperty('sourceVpcName')) {
        obj['sourceVpcName'] = ApiClient.convertToType(data['sourceVpcName'], 'String');
      }
      if (data.hasOwnProperty('vpcPeeringName')) {
        obj['vpcPeeringName'] = ApiClient.convertToType(data['vpcPeeringName'], 'String');
      }
      if (data.hasOwnProperty('targetVpcName')) {
        obj['targetVpcName'] = ApiClient.convertToType(data['targetVpcName'], 'String');
      }
      if (data.hasOwnProperty('vpcPeeringInstanceStatusCode')) {
        obj['vpcPeeringInstanceStatusCode'] = ApiClient.convertToType(data['vpcPeeringInstanceStatusCode'], 'String');
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('sortedBy')) {
        obj['sortedBy'] = ApiClient.convertToType(data['sortedBy'], 'String');
      }
      if (data.hasOwnProperty('sortingOrder')) {
        obj['sortingOrder'] = ApiClient.convertToType(data['sortingOrder'], 'String');
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * VPCPeering인스턴스번호리스트
   * @member {Array.<String>} vpcPeeringInstanceNoList
   */
  exports.prototype['vpcPeeringInstanceNoList'] = undefined;
  /**
   * 요청VPC이름
   * @member {String} sourceVpcName
   */
  exports.prototype['sourceVpcName'] = undefined;
  /**
   * VPCPeering이름
   * @member {String} vpcPeeringName
   */
  exports.prototype['vpcPeeringName'] = undefined;
  /**
   * 수락VPC이름
   * @member {String} targetVpcName
   */
  exports.prototype['targetVpcName'] = undefined;
  /**
   * VPCPeering인스턴스상태코드
   * @member {String} vpcPeeringInstanceStatusCode
   */
  exports.prototype['vpcPeeringInstanceStatusCode'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * 정렬대상
   * @member {String} sortedBy
   */
  exports.prototype['sortedBy'] = undefined;
  /**
   * 정렬순서
   * @member {String} sortingOrder
   */
  exports.prototype['sortingOrder'] = undefined;



  return exports;
}));


