/*
* vpc
* VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
*
* OpenAPI spec version: 2020-09-17T02:27:03Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CommonCode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CommonCode'));
  } else {
    // Browser globals (root is window)
    if (!root.Vpc) {
      root.Vpc = {};
    }
    root.Vpc.Route = factory(root.Vpc.ApiClient, root.Vpc.CommonCode);
  }
}(this, function(ApiClient, CommonCode) {
  'use strict';




  /**
   * The Route model module.
   * @module model/Route
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Route</code>.
   * @alias module:model/Route
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Route</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Route} obj Optional instance to populate.
   * @return {module:model/Route} The populated <code>Route</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('destinationCidrBlock')) {
        obj['destinationCidrBlock'] = ApiClient.convertToType(data['destinationCidrBlock'], 'String');
      }
      if (data.hasOwnProperty('targetName')) {
        obj['targetName'] = ApiClient.convertToType(data['targetName'], 'String');
      }
      if (data.hasOwnProperty('routeTableNo')) {
        obj['routeTableNo'] = ApiClient.convertToType(data['routeTableNo'], 'String');
      }
      if (data.hasOwnProperty('targetType')) {
        obj['targetType'] = CommonCode.constructFromObject(data['targetType']);
      }
      if (data.hasOwnProperty('targetNo')) {
        obj['targetNo'] = ApiClient.convertToType(data['targetNo'], 'String');
      }
      if (data.hasOwnProperty('isDefault')) {
        obj['isDefault'] = ApiClient.convertToType(data['isDefault'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * 목적지CIDR블록
   * @member {String} destinationCidrBlock
   */
  exports.prototype['destinationCidrBlock'] = undefined;
  /**
   * 목적지이름
   * @member {String} targetName
   */
  exports.prototype['targetName'] = undefined;
  /**
   * 라우트테이블번호
   * @member {String} routeTableNo
   */
  exports.prototype['routeTableNo'] = undefined;
  /**
   * 목적지유형
   * @member {module:model/CommonCode} targetType
   */
  exports.prototype['targetType'] = undefined;
  /**
   * 목적지번호
   * @member {String} targetNo
   */
  exports.prototype['targetNo'] = undefined;
  /**
   * Default여부
   * @member {Boolean} isDefault
   */
  exports.prototype['isDefault'] = undefined;



  return exports;
}));


