/*
* vpc
* VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
*
* OpenAPI spec version: 2020-09-17T02:27:03Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vpc) {
      root.Vpc = {};
    }
    root.Vpc.RouteParameter = factory(root.Vpc.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RouteParameter model module.
   * @module model/RouteParameter
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RouteParameter</code>.
   * @alias module:model/RouteParameter
   * @class
   * @param destinationCidrBlock {String} 목적지CIDR블록
   * @param targetTypeCode {String} 목적지유형코드
   */
  var exports = function(destinationCidrBlock, targetTypeCode) {
    var _this = this;

    _this['destinationCidrBlock'] = destinationCidrBlock;
    _this['targetTypeCode'] = targetTypeCode;


  };

  /**
   * Constructs a <code>RouteParameter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RouteParameter} obj Optional instance to populate.
   * @return {module:model/RouteParameter} The populated <code>RouteParameter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('destinationCidrBlock')) {
        obj['destinationCidrBlock'] = ApiClient.convertToType(data['destinationCidrBlock'], 'String');
      }
      if (data.hasOwnProperty('targetTypeCode')) {
        obj['targetTypeCode'] = ApiClient.convertToType(data['targetTypeCode'], 'String');
      }
      if (data.hasOwnProperty('targetNo')) {
        obj['targetNo'] = ApiClient.convertToType(data['targetNo'], 'String');
      }
      if (data.hasOwnProperty('targetName')) {
        obj['targetName'] = ApiClient.convertToType(data['targetName'], 'String');
      }
    }
    return obj;
  }

  /**
   * 목적지CIDR블록
   * @member {String} destinationCidrBlock
   */
  exports.prototype['destinationCidrBlock'] = undefined;
  /**
   * 목적지유형코드
   * @member {String} targetTypeCode
   */
  exports.prototype['targetTypeCode'] = undefined;
  /**
   * 목적지번호
   * @member {String} targetNo
   */
  exports.prototype['targetNo'] = undefined;
  /**
   * 목적지이름
   * @member {String} targetName
   */
  exports.prototype['targetName'] = undefined;



  return exports;
}));


