/*
* vpc
* VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vpc) {
      root.Vpc = {};
    }
    root.Vpc.SetNatGatewayDescriptionRequest = factory(root.Vpc.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SetNatGatewayDescriptionRequest model module.
   * @module model/SetNatGatewayDescriptionRequest
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>SetNatGatewayDescriptionRequest</code>.
   * @alias module:model/SetNatGatewayDescriptionRequest
   * @class
   * @param natGatewayInstanceNo {String} NATGateway인스턴스번호
   */
  var exports = function(natGatewayInstanceNo) {
    var _this = this;


    _this['natGatewayInstanceNo'] = natGatewayInstanceNo;

  };

  /**
   * Constructs a <code>SetNatGatewayDescriptionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SetNatGatewayDescriptionRequest} obj Optional instance to populate.
   * @return {module:model/SetNatGatewayDescriptionRequest} The populated <code>SetNatGatewayDescriptionRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('natGatewayInstanceNo')) {
        obj['natGatewayInstanceNo'] = ApiClient.convertToType(data['natGatewayInstanceNo'], 'String');
      }
      if (data.hasOwnProperty('natGatewayDescription')) {
        obj['natGatewayDescription'] = ApiClient.convertToType(data['natGatewayDescription'], 'String');
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * NATGateway인스턴스번호
   * @member {String} natGatewayInstanceNo
   */
  exports.prototype['natGatewayInstanceNo'] = undefined;
  /**
   * NATGateway설명
   * @member {String} natGatewayDescription
   */
  exports.prototype['natGatewayDescription'] = undefined;



  return exports;
}));


