/*
* server
* <br/>https://ncloud.apigw.ntruss.com/server/v2
*
* OpenAPI spec version: 2018-07-02T09:06:17Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    factory(require('expect.js'), require('../../src/index'));
  } else {
    factory(root.expect, root.Server);
  }
}(this, function(expect, Server) {
  'use strict';

  var client = new Server.ApiClient({
    accessKey: 'your access key',
    secretKey: 'your secret key'
  });
  var instance = new Server.V2Api(client);

  describe('V2Api', function() {
    describe('addNasVolumeAccessControl', function() {
      it('should call addNasVolumeAccessControl successfully', function(done) {
        //uncomment below and update the code to test addNasVolumeAccessControl
        //instance.addNasVolumeAccessControl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('addPortForwardingRules', function() {
      it('should call addPortForwardingRules successfully', function(done) {
        //uncomment below and update the code to test addPortForwardingRules
        //instance.addPortForwardingRules(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('associatePublicIpWithServerInstance', function() {
      it('should call associatePublicIpWithServerInstance successfully', function(done) {
        //uncomment below and update the code to test associatePublicIpWithServerInstance
        //instance.associatePublicIpWithServerInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('changeNasVolumeSize', function() {
      it('should call changeNasVolumeSize successfully', function(done) {
        //uncomment below and update the code to test changeNasVolumeSize
        //instance.changeNasVolumeSize(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('changeServerInstanceSpec', function() {
      it('should call changeServerInstanceSpec successfully', function(done) {
        //uncomment below and update the code to test changeServerInstanceSpec
        //instance.changeServerInstanceSpec(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createBlockStorageInstance', function() {
      it('should call createBlockStorageInstance successfully', function(done) {
        //uncomment below and update the code to test createBlockStorageInstance
        //instance.createBlockStorageInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createLoginKey', function() {
      it('should call createLoginKey successfully', function(done) {
        //uncomment below and update the code to test createLoginKey
        //instance.createLoginKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createMemberServerImage', function() {
      it('should call createMemberServerImage successfully', function(done) {
        //uncomment below and update the code to test createMemberServerImage
        //instance.createMemberServerImage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createNasVolumeInstance', function() {
      it('should call createNasVolumeInstance successfully', function(done) {
        //uncomment below and update the code to test createNasVolumeInstance
        //instance.createNasVolumeInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createPublicIpInstance', function() {
      it('should call createPublicIpInstance successfully', function(done) {
        //uncomment below and update the code to test createPublicIpInstance
        //instance.createPublicIpInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createServerInstances', function() {
      it('should call createServerInstances successfully', function(done) {
        //uncomment below and update the code to test createServerInstances
        //instance.createServerInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteBlockStorageInstances', function() {
      it('should call deleteBlockStorageInstances successfully', function(done) {
        //uncomment below and update the code to test deleteBlockStorageInstances
        //instance.deleteBlockStorageInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteLoginKey', function() {
      it('should call deleteLoginKey successfully', function(done) {
        //uncomment below and update the code to test deleteLoginKey
        //instance.deleteLoginKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteMemberServerImages', function() {
      it('should call deleteMemberServerImages successfully', function(done) {
        //uncomment below and update the code to test deleteMemberServerImages
        //instance.deleteMemberServerImages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteNasVolumeInstance', function() {
      it('should call deleteNasVolumeInstance successfully', function(done) {
        //uncomment below and update the code to test deleteNasVolumeInstance
        //instance.deleteNasVolumeInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deletePortForwardingRules', function() {
      it('should call deletePortForwardingRules successfully', function(done) {
        //uncomment below and update the code to test deletePortForwardingRules
        //instance.deletePortForwardingRules(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deletePublicIpInstances', function() {
      it('should call deletePublicIpInstances successfully', function(done) {
        //uncomment below and update the code to test deletePublicIpInstances
        //instance.deletePublicIpInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('disassociatePublicIpFromServerInstance', function() {
      it('should call disassociatePublicIpFromServerInstance successfully', function(done) {
        //uncomment below and update the code to test disassociatePublicIpFromServerInstance
        //instance.disassociatePublicIpFromServerInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getAccessControlGroupList', function() {
      it('should call getAccessControlGroupList successfully', function(done) {
        //uncomment below and update the code to test getAccessControlGroupList
        //instance.getAccessControlGroupList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getAccessControlGroupServerInstanceList', function() {
      it('should call getAccessControlGroupServerInstanceList successfully', function(done) {
        //uncomment below and update the code to test getAccessControlGroupServerInstanceList
        //instance.getAccessControlGroupServerInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getAccessControlRuleList', function() {
      it('should call getAccessControlRuleList successfully', function(done) {
        //uncomment below and update the code to test getAccessControlRuleList
        //instance.getAccessControlRuleList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getBlockStorageInstanceList', function() {
      it('should call getBlockStorageInstanceList successfully', function(done) {
        //uncomment below and update the code to test getBlockStorageInstanceList
        //instance.getBlockStorageInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getBlockStorageSnapshotInstanceList', function() {
      it('should call getBlockStorageSnapshotInstanceList successfully', function(done) {
        //uncomment below and update the code to test getBlockStorageSnapshotInstanceList
        //instance.getBlockStorageSnapshotInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getLoginKeyList', function() {
      it('should call getLoginKeyList successfully', function(done) {
        //uncomment below and update the code to test getLoginKeyList
        //instance.getLoginKeyList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getMemberServerImageList', function() {
      it('should call getMemberServerImageList successfully', function(done) {
        //uncomment below and update the code to test getMemberServerImageList
        //instance.getMemberServerImageList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getNasVolumeInstanceList', function() {
      it('should call getNasVolumeInstanceList successfully', function(done) {
        //uncomment below and update the code to test getNasVolumeInstanceList
        //instance.getNasVolumeInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getNasVolumeInstanceRatingList', function() {
      it('should call getNasVolumeInstanceRatingList successfully', function(done) {
        //uncomment below and update the code to test getNasVolumeInstanceRatingList
        //instance.getNasVolumeInstanceRatingList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getPortForwardingRuleList', function() {
      it('should call getPortForwardingRuleList successfully', function(done) {
        //uncomment below and update the code to test getPortForwardingRuleList
        //instance.getPortForwardingRuleList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getPublicIpInstanceList', function() {
      it('should call getPublicIpInstanceList successfully', function(done) {
        //uncomment below and update the code to test getPublicIpInstanceList
        //instance.getPublicIpInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getPublicIpTargetServerInstanceList', function() {
      it('should call getPublicIpTargetServerInstanceList successfully', function(done) {
        //uncomment below and update the code to test getPublicIpTargetServerInstanceList
        //instance.getPublicIpTargetServerInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getRaidList', function() {
      it('should call getRaidList successfully', function(done) {
        //uncomment below and update the code to test getRaidList
        //instance.getRaidList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getRegionList', function() {
      it('should call getRegionList successfully', function(done) {
        //uncomment below and update the code to test getRegionList
        //instance.getRegionList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getRootPassword', function() {
      it('should call getRootPassword successfully', function(done) {
        //uncomment below and update the code to test getRootPassword
        //instance.getRootPassword(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getServerImageProductList', function() {
      it('should call getServerImageProductList successfully', function(done) {
        //uncomment below and update the code to test getServerImageProductList
        //instance.getServerImageProductList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getServerInstanceList', function() {
      it('should call getServerInstanceList successfully', function(done) {
        //uncomment below and update the code to test getServerInstanceList
        //instance.getServerInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getServerProductList', function() {
      it('should call getServerProductList successfully', function(done) {
        //uncomment below and update the code to test getServerProductList
        //instance.getServerProductList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getZoneList', function() {
      it('should call getZoneList successfully', function(done) {
        //uncomment below and update the code to test getZoneList
        //instance.getZoneList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('rebootServerInstances', function() {
      it('should call rebootServerInstances successfully', function(done) {
        //uncomment below and update the code to test rebootServerInstances
        //instance.rebootServerInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('recreateServerInstance', function() {
      it('should call recreateServerInstance successfully', function(done) {
        //uncomment below and update the code to test recreateServerInstance
        //instance.recreateServerInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('removeNasVolumeAccessControl', function() {
      it('should call removeNasVolumeAccessControl successfully', function(done) {
        //uncomment below and update the code to test removeNasVolumeAccessControl
        //instance.removeNasVolumeAccessControl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('setNasVolumeAccessControl', function() {
      it('should call setNasVolumeAccessControl successfully', function(done) {
        //uncomment below and update the code to test setNasVolumeAccessControl
        //instance.setNasVolumeAccessControl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('startServerInstances', function() {
      it('should call startServerInstances successfully', function(done) {
        //uncomment below and update the code to test startServerInstances
        //instance.startServerInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('stopServerInstances', function() {
      it('should call stopServerInstances successfully', function(done) {
        //uncomment below and update the code to test stopServerInstances
        //instance.stopServerInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('terminateServerInstances', function() {
      it('should call terminateServerInstances successfully', function(done) {
        //uncomment below and update the code to test terminateServerInstances
        //instance.terminateServerInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
  });

}));
