/*
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.ncloud.clouddb.model/AccessControlGroup', 'com.ncloud.clouddb.model/CloudDBConfig', 'com.ncloud.clouddb.model/CloudDBConfigGroup', 'com.ncloud.clouddb.model/CloudDBInstance', 'com.ncloud.clouddb.model/CloudDBServerInstance', 'com.ncloud.clouddb.model/CommonCode', 'com.ncloud.clouddb.model/CreateCloudDBInstanceRequest', 'com.ncloud.clouddb.model/CreateCloudDBInstanceResponse', 'com.ncloud.clouddb.model/DeleteCloudDBServerInstanceRequest', 'com.ncloud.clouddb.model/DeleteCloudDBServerInstanceResponse', 'com.ncloud.clouddb.model/GetCloudDBConfigGroupListRequest', 'com.ncloud.clouddb.model/GetCloudDBConfigGroupListResponse', 'com.ncloud.clouddb.model/GetCloudDBImageProductListRequest', 'com.ncloud.clouddb.model/GetCloudDBImageProductListResponse', 'com.ncloud.clouddb.model/GetCloudDBInstanceListRequest', 'com.ncloud.clouddb.model/GetCloudDBInstanceListResponse', 'com.ncloud.clouddb.model/GetCloudDBProductListRequest', 'com.ncloud.clouddb.model/GetCloudDBProductListResponse', 'com.ncloud.clouddb.model/Product', 'com.ncloud.clouddb.model/RebootCloudDBServerInstanceRequest', 'com.ncloud.clouddb.model/RebootCloudDBServerInstanceResponse', 'com.ncloud.clouddb.model/Region', 'com.ncloud.clouddb.model/Zone', 'com.ncloud.clouddb.api/V2Api'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./com.ncloud.clouddb.model/AccessControlGroup'), require('./com.ncloud.clouddb.model/CloudDBConfig'), require('./com.ncloud.clouddb.model/CloudDBConfigGroup'), require('./com.ncloud.clouddb.model/CloudDBInstance'), require('./com.ncloud.clouddb.model/CloudDBServerInstance'), require('./com.ncloud.clouddb.model/CommonCode'), require('./com.ncloud.clouddb.model/CreateCloudDBInstanceRequest'), require('./com.ncloud.clouddb.model/CreateCloudDBInstanceResponse'), require('./com.ncloud.clouddb.model/DeleteCloudDBServerInstanceRequest'), require('./com.ncloud.clouddb.model/DeleteCloudDBServerInstanceResponse'), require('./com.ncloud.clouddb.model/GetCloudDBConfigGroupListRequest'), require('./com.ncloud.clouddb.model/GetCloudDBConfigGroupListResponse'), require('./com.ncloud.clouddb.model/GetCloudDBImageProductListRequest'), require('./com.ncloud.clouddb.model/GetCloudDBImageProductListResponse'), require('./com.ncloud.clouddb.model/GetCloudDBInstanceListRequest'), require('./com.ncloud.clouddb.model/GetCloudDBInstanceListResponse'), require('./com.ncloud.clouddb.model/GetCloudDBProductListRequest'), require('./com.ncloud.clouddb.model/GetCloudDBProductListResponse'), require('./com.ncloud.clouddb.model/Product'), require('./com.ncloud.clouddb.model/RebootCloudDBServerInstanceRequest'), require('./com.ncloud.clouddb.model/RebootCloudDBServerInstanceResponse'), require('./com.ncloud.clouddb.model/Region'), require('./com.ncloud.clouddb.model/Zone'), require('./com.ncloud.clouddb.api/V2Api'));
  }
}(function(ApiClient, AccessControlGroup, CloudDBConfig, CloudDBConfigGroup, CloudDBInstance, CloudDBServerInstance, CommonCode, CreateCloudDBInstanceRequest, CreateCloudDBInstanceResponse, DeleteCloudDBServerInstanceRequest, DeleteCloudDBServerInstanceResponse, GetCloudDBConfigGroupListRequest, GetCloudDBConfigGroupListResponse, GetCloudDBImageProductListRequest, GetCloudDBImageProductListResponse, GetCloudDBInstanceListRequest, GetCloudDBInstanceListResponse, GetCloudDBProductListRequest, GetCloudDBProductListResponse, Product, RebootCloudDBServerInstanceRequest, RebootCloudDBServerInstanceResponse, Region, Zone, V2Api) {
  'use strict';

  /**
   * Cloud DB&lt;br/&gt;https://ncloud.beta-apigw.ntruss.com/clouddb/v2.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Clouddb = require('index'); // See note below*.
   * var xxxSvc = new Clouddb.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Clouddb.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Clouddb.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Clouddb.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AccessControlGroup model constructor.
     * @property {module:com.ncloud.clouddb.model/AccessControlGroup}
     */
    AccessControlGroup: AccessControlGroup,
    /**
     * The CloudDBConfig model constructor.
     * @property {module:com.ncloud.clouddb.model/CloudDBConfig}
     */
    CloudDBConfig: CloudDBConfig,
    /**
     * The CloudDBConfigGroup model constructor.
     * @property {module:com.ncloud.clouddb.model/CloudDBConfigGroup}
     */
    CloudDBConfigGroup: CloudDBConfigGroup,
    /**
     * The CloudDBInstance model constructor.
     * @property {module:com.ncloud.clouddb.model/CloudDBInstance}
     */
    CloudDBInstance: CloudDBInstance,
    /**
     * The CloudDBServerInstance model constructor.
     * @property {module:com.ncloud.clouddb.model/CloudDBServerInstance}
     */
    CloudDBServerInstance: CloudDBServerInstance,
    /**
     * The CommonCode model constructor.
     * @property {module:com.ncloud.clouddb.model/CommonCode}
     */
    CommonCode: CommonCode,
    /**
     * The CreateCloudDBInstanceRequest model constructor.
     * @property {module:com.ncloud.clouddb.model/CreateCloudDBInstanceRequest}
     */
    CreateCloudDBInstanceRequest: CreateCloudDBInstanceRequest,
    /**
     * The CreateCloudDBInstanceResponse model constructor.
     * @property {module:com.ncloud.clouddb.model/CreateCloudDBInstanceResponse}
     */
    CreateCloudDBInstanceResponse: CreateCloudDBInstanceResponse,
    /**
     * The DeleteCloudDBServerInstanceRequest model constructor.
     * @property {module:com.ncloud.clouddb.model/DeleteCloudDBServerInstanceRequest}
     */
    DeleteCloudDBServerInstanceRequest: DeleteCloudDBServerInstanceRequest,
    /**
     * The DeleteCloudDBServerInstanceResponse model constructor.
     * @property {module:com.ncloud.clouddb.model/DeleteCloudDBServerInstanceResponse}
     */
    DeleteCloudDBServerInstanceResponse: DeleteCloudDBServerInstanceResponse,
    /**
     * The GetCloudDBConfigGroupListRequest model constructor.
     * @property {module:com.ncloud.clouddb.model/GetCloudDBConfigGroupListRequest}
     */
    GetCloudDBConfigGroupListRequest: GetCloudDBConfigGroupListRequest,
    /**
     * The GetCloudDBConfigGroupListResponse model constructor.
     * @property {module:com.ncloud.clouddb.model/GetCloudDBConfigGroupListResponse}
     */
    GetCloudDBConfigGroupListResponse: GetCloudDBConfigGroupListResponse,
    /**
     * The GetCloudDBImageProductListRequest model constructor.
     * @property {module:com.ncloud.clouddb.model/GetCloudDBImageProductListRequest}
     */
    GetCloudDBImageProductListRequest: GetCloudDBImageProductListRequest,
    /**
     * The GetCloudDBImageProductListResponse model constructor.
     * @property {module:com.ncloud.clouddb.model/GetCloudDBImageProductListResponse}
     */
    GetCloudDBImageProductListResponse: GetCloudDBImageProductListResponse,
    /**
     * The GetCloudDBInstanceListRequest model constructor.
     * @property {module:com.ncloud.clouddb.model/GetCloudDBInstanceListRequest}
     */
    GetCloudDBInstanceListRequest: GetCloudDBInstanceListRequest,
    /**
     * The GetCloudDBInstanceListResponse model constructor.
     * @property {module:com.ncloud.clouddb.model/GetCloudDBInstanceListResponse}
     */
    GetCloudDBInstanceListResponse: GetCloudDBInstanceListResponse,
    /**
     * The GetCloudDBProductListRequest model constructor.
     * @property {module:com.ncloud.clouddb.model/GetCloudDBProductListRequest}
     */
    GetCloudDBProductListRequest: GetCloudDBProductListRequest,
    /**
     * The GetCloudDBProductListResponse model constructor.
     * @property {module:com.ncloud.clouddb.model/GetCloudDBProductListResponse}
     */
    GetCloudDBProductListResponse: GetCloudDBProductListResponse,
    /**
     * The Product model constructor.
     * @property {module:com.ncloud.clouddb.model/Product}
     */
    Product: Product,
    /**
     * The RebootCloudDBServerInstanceRequest model constructor.
     * @property {module:com.ncloud.clouddb.model/RebootCloudDBServerInstanceRequest}
     */
    RebootCloudDBServerInstanceRequest: RebootCloudDBServerInstanceRequest,
    /**
     * The RebootCloudDBServerInstanceResponse model constructor.
     * @property {module:com.ncloud.clouddb.model/RebootCloudDBServerInstanceResponse}
     */
    RebootCloudDBServerInstanceResponse: RebootCloudDBServerInstanceResponse,
    /**
     * The Region model constructor.
     * @property {module:com.ncloud.clouddb.model/Region}
     */
    Region: Region,
    /**
     * The Zone model constructor.
     * @property {module:com.ncloud.clouddb.model/Zone}
     */
    Zone: Zone,
    /**
     * The V2Api service constructor.
     * @property {module:com.ncloud.clouddb.api/V2Api}
     */
    V2Api: V2Api
  };

  return exports;
}));
