/*
* monitoring
* <br/>https://ncloud.apigw.ntruss.com/monitoring/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    factory(require('expect.js'), require('../../src/index'));
  } else {
    factory(root.expect, root.Monitoring);
  }
}(this, function(expect, Monitoring) {
  'use strict';

  var client = new Monitoring.ApiClient({
    accessKey: 'your access key',
    secretKey: 'your secret key'
  });
  var instance = new Monitoring.V2Api(client);

  describe('V2Api', function() {
    describe('getListMetrics', function() {
      it('should call getListMetrics successfully', function(done) {
        //uncomment below and update the code to test getListMetrics
        //instance.getListMetrics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getMetricStatisticList', function() {
      it('should call getMetricStatisticList successfully', function(done) {
        //uncomment below and update the code to test getMetricStatisticList
        //instance.getMetricStatisticList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
  });

}));
