/*
* vserver
* VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CommonCode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CommonCode'));
  } else {
    // Browser globals (root is window)
    if (!root.Vserver) {
      root.Vserver = {};
    }
    root.Vserver.AccessControlGroupRule = factory(root.Vserver.ApiClient, root.Vserver.CommonCode);
  }
}(this, function(ApiClient, CommonCode) {
  'use strict';




  /**
   * The AccessControlGroupRule model module.
   * @module model/AccessControlGroupRule
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>AccessControlGroupRule</code>.
   * @alias module:model/AccessControlGroupRule
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>AccessControlGroupRule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccessControlGroupRule} obj Optional instance to populate.
   * @return {module:model/AccessControlGroupRule} The populated <code>AccessControlGroupRule</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accessControlGroupNo')) {
        obj['accessControlGroupNo'] = ApiClient.convertToType(data['accessControlGroupNo'], 'String');
      }
      if (data.hasOwnProperty('protocolType')) {
        obj['protocolType'] = CommonCode.constructFromObject(data['protocolType']);
      }
      if (data.hasOwnProperty('ipBlock')) {
        obj['ipBlock'] = ApiClient.convertToType(data['ipBlock'], 'String');
      }
      if (data.hasOwnProperty('portRange')) {
        obj['portRange'] = ApiClient.convertToType(data['portRange'], 'String');
      }
      if (data.hasOwnProperty('accessControlGroupSequence')) {
        obj['accessControlGroupSequence'] = ApiClient.convertToType(data['accessControlGroupSequence'], 'String');
      }
      if (data.hasOwnProperty('accessControlGroupRuleType')) {
        obj['accessControlGroupRuleType'] = CommonCode.constructFromObject(data['accessControlGroupRuleType']);
      }
      if (data.hasOwnProperty('accessControlGroupRuleDescription')) {
        obj['accessControlGroupRuleDescription'] = ApiClient.convertToType(data['accessControlGroupRuleDescription'], 'String');
      }
    }
    return obj;
  }

  /**
   * ACG번호
   * @member {String} accessControlGroupNo
   */
  exports.prototype['accessControlGroupNo'] = undefined;
  /**
   * 프로토콜유형
   * @member {module:model/CommonCode} protocolType
   */
  exports.prototype['protocolType'] = undefined;
  /**
   * IP블록
   * @member {String} ipBlock
   */
  exports.prototype['ipBlock'] = undefined;
  /**
   * 포트범위
   * @member {String} portRange
   */
  exports.prototype['portRange'] = undefined;
  /**
   * 접근소스ACG
   * @member {String} accessControlGroupSequence
   */
  exports.prototype['accessControlGroupSequence'] = undefined;
  /**
   * ACGRule유형
   * @member {module:model/CommonCode} accessControlGroupRuleType
   */
  exports.prototype['accessControlGroupRuleType'] = undefined;
  /**
   * ACGRule설명
   * @member {String} accessControlGroupRuleDescription
   */
  exports.prototype['accessControlGroupRuleDescription'] = undefined;



  return exports;
}));


