/*
* vserver
* VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
*
* OpenAPI spec version: 2020-09-17T02:28:03Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vserver) {
      root.Vserver = {};
    }
    root.Vserver.DeleteInitScriptsRequest = factory(root.Vserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeleteInitScriptsRequest model module.
   * @module model/DeleteInitScriptsRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DeleteInitScriptsRequest</code>.
   * @alias module:model/DeleteInitScriptsRequest
   * @class
   * @param initScriptNoList {Array.<String>} 초기화스크립트번호리스트
   */
  var exports = function(initScriptNoList) {
    var _this = this;


    _this['initScriptNoList'] = initScriptNoList;
  };

  /**
   * Constructs a <code>DeleteInitScriptsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeleteInitScriptsRequest} obj Optional instance to populate.
   * @return {module:model/DeleteInitScriptsRequest} The populated <code>DeleteInitScriptsRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('initScriptNoList')) {
        obj['initScriptNoList'] = ApiClient.convertToType(data['initScriptNoList'], ['String']);
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * 초기화스크립트번호리스트
   * @member {Array.<String>} initScriptNoList
   */
  exports.prototype['initScriptNoList'] = undefined;



  return exports;
}));


