/*
* vserver
* VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vserver) {
      root.Vserver = {};
    }
    root.Vserver.GetAccessControlGroupListRequest = factory(root.Vserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetAccessControlGroupListRequest model module.
   * @module model/GetAccessControlGroupListRequest
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>GetAccessControlGroupListRequest</code>.
   * @alias module:model/GetAccessControlGroupListRequest
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>GetAccessControlGroupListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAccessControlGroupListRequest} obj Optional instance to populate.
   * @return {module:model/GetAccessControlGroupListRequest} The populated <code>GetAccessControlGroupListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('accessControlGroupNoList')) {
        obj['accessControlGroupNoList'] = ApiClient.convertToType(data['accessControlGroupNoList'], ['String']);
      }
      if (data.hasOwnProperty('accessControlGroupName')) {
        obj['accessControlGroupName'] = ApiClient.convertToType(data['accessControlGroupName'], 'String');
      }
      if (data.hasOwnProperty('accessControlGroupStatusCode')) {
        obj['accessControlGroupStatusCode'] = ApiClient.convertToType(data['accessControlGroupStatusCode'], 'String');
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('vpcNo')) {
        obj['vpcNo'] = ApiClient.convertToType(data['vpcNo'], 'String');
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * ACG번호리스트
   * @member {Array.<String>} accessControlGroupNoList
   */
  exports.prototype['accessControlGroupNoList'] = undefined;
  /**
   * ACG이름
   * @member {String} accessControlGroupName
   */
  exports.prototype['accessControlGroupName'] = undefined;
  /**
   * ACG상태코드
   * @member {String} accessControlGroupStatusCode
   */
  exports.prototype['accessControlGroupStatusCode'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * VPC번호
   * @member {String} vpcNo
   */
  exports.prototype['vpcNo'] = undefined;



  return exports;
}));


