/*
* vserver
* VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
*
* OpenAPI spec version: 2020-09-17T02:28:03Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vserver) {
      root.Vserver = {};
    }
    root.Vserver.GetBlockStorageInstanceListRequest = factory(root.Vserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetBlockStorageInstanceListRequest model module.
   * @module model/GetBlockStorageInstanceListRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetBlockStorageInstanceListRequest</code>.
   * @alias module:model/GetBlockStorageInstanceListRequest
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>GetBlockStorageInstanceListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetBlockStorageInstanceListRequest} obj Optional instance to populate.
   * @return {module:model/GetBlockStorageInstanceListRequest} The populated <code>GetBlockStorageInstanceListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('serverInstanceNo')) {
        obj['serverInstanceNo'] = ApiClient.convertToType(data['serverInstanceNo'], 'String');
      }
      if (data.hasOwnProperty('blockStorageTypeCodeList')) {
        obj['blockStorageTypeCodeList'] = ApiClient.convertToType(data['blockStorageTypeCodeList'], ['String']);
      }
      if (data.hasOwnProperty('blockStorageInstanceStatusCode')) {
        obj['blockStorageInstanceStatusCode'] = ApiClient.convertToType(data['blockStorageInstanceStatusCode'], 'String');
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('blockStorageSize')) {
        obj['blockStorageSize'] = ApiClient.convertToType(data['blockStorageSize'], 'Number');
      }
      if (data.hasOwnProperty('blockStorageInstanceNoList')) {
        obj['blockStorageInstanceNoList'] = ApiClient.convertToType(data['blockStorageInstanceNoList'], ['String']);
      }
      if (data.hasOwnProperty('blockStorageName')) {
        obj['blockStorageName'] = ApiClient.convertToType(data['blockStorageName'], 'String');
      }
      if (data.hasOwnProperty('serverName')) {
        obj['serverName'] = ApiClient.convertToType(data['serverName'], 'String');
      }
      if (data.hasOwnProperty('connectionInfo')) {
        obj['connectionInfo'] = ApiClient.convertToType(data['connectionInfo'], 'String');
      }
      if (data.hasOwnProperty('blockStorageDiskTypeCode')) {
        obj['blockStorageDiskTypeCode'] = ApiClient.convertToType(data['blockStorageDiskTypeCode'], 'String');
      }
      if (data.hasOwnProperty('blockStorageDiskDetailTypeCode')) {
        obj['blockStorageDiskDetailTypeCode'] = ApiClient.convertToType(data['blockStorageDiskDetailTypeCode'], 'String');
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * 서버인스턴스번호
   * @member {String} serverInstanceNo
   */
  exports.prototype['serverInstanceNo'] = undefined;
  /**
   * 블록스토리지유형코드리스트
   * @member {Array.<String>} blockStorageTypeCodeList
   */
  exports.prototype['blockStorageTypeCodeList'] = undefined;
  /**
   * 블록스토리지인스턴스상태코드
   * @member {String} blockStorageInstanceStatusCode
   */
  exports.prototype['blockStorageInstanceStatusCode'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * 블록스토리지사이즈
   * @member {Number} blockStorageSize
   */
  exports.prototype['blockStorageSize'] = undefined;
  /**
   * 블록스토리지인스턴스번호리스트
   * @member {Array.<String>} blockStorageInstanceNoList
   */
  exports.prototype['blockStorageInstanceNoList'] = undefined;
  /**
   * 블록스토리지이름
   * @member {String} blockStorageName
   */
  exports.prototype['blockStorageName'] = undefined;
  /**
   * 서버이름
   * @member {String} serverName
   */
  exports.prototype['serverName'] = undefined;
  /**
   * 연결정보
   * @member {String} connectionInfo
   */
  exports.prototype['connectionInfo'] = undefined;
  /**
   * 블록스토리지디스크유형코드
   * @member {String} blockStorageDiskTypeCode
   */
  exports.prototype['blockStorageDiskTypeCode'] = undefined;
  /**
   * 블록스토리지디스크상세유형코드
   * @member {String} blockStorageDiskDetailTypeCode
   */
  exports.prototype['blockStorageDiskDetailTypeCode'] = undefined;



  return exports;
}));


