/*
* vserver
* VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
*
* OpenAPI spec version: 2020-09-17T02:28:03Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vserver) {
      root.Vserver = {};
    }
    root.Vserver.GetMemberServerImageInstanceListRequest = factory(root.Vserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetMemberServerImageInstanceListRequest model module.
   * @module model/GetMemberServerImageInstanceListRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetMemberServerImageInstanceListRequest</code>.
   * @alias module:model/GetMemberServerImageInstanceListRequest
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>GetMemberServerImageInstanceListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetMemberServerImageInstanceListRequest} obj Optional instance to populate.
   * @return {module:model/GetMemberServerImageInstanceListRequest} The populated <code>GetMemberServerImageInstanceListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('memberServerImageName')) {
        obj['memberServerImageName'] = ApiClient.convertToType(data['memberServerImageName'], 'String');
      }
      if (data.hasOwnProperty('memberServerImageInstanceStatusCode')) {
        obj['memberServerImageInstanceStatusCode'] = ApiClient.convertToType(data['memberServerImageInstanceStatusCode'], 'String');
      }
      if (data.hasOwnProperty('memberServerImageInstanceNoList')) {
        obj['memberServerImageInstanceNoList'] = ApiClient.convertToType(data['memberServerImageInstanceNoList'], ['String']);
      }
      if (data.hasOwnProperty('platformTypeCodeList')) {
        obj['platformTypeCodeList'] = ApiClient.convertToType(data['platformTypeCodeList'], ['String']);
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('sortedBy')) {
        obj['sortedBy'] = ApiClient.convertToType(data['sortedBy'], 'String');
      }
      if (data.hasOwnProperty('sortingOrder')) {
        obj['sortingOrder'] = ApiClient.convertToType(data['sortingOrder'], 'String');
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * 회원서버이미지이름
   * @member {String} memberServerImageName
   */
  exports.prototype['memberServerImageName'] = undefined;
  /**
   * 회원서버이미지인스턴스상태코드
   * @member {String} memberServerImageInstanceStatusCode
   */
  exports.prototype['memberServerImageInstanceStatusCode'] = undefined;
  /**
   * 회원서버이미지인스턴스번호리스트
   * @member {Array.<String>} memberServerImageInstanceNoList
   */
  exports.prototype['memberServerImageInstanceNoList'] = undefined;
  /**
   * 플랫폼유형코드리스트
   * @member {Array.<String>} platformTypeCodeList
   */
  exports.prototype['platformTypeCodeList'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * 정렬대상
   * @member {String} sortedBy
   */
  exports.prototype['sortedBy'] = undefined;
  /**
   * 정렬순서
   * @member {String} sortingOrder
   */
  exports.prototype['sortingOrder'] = undefined;



  return exports;
}));


