/*
* vserver
* VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vserver) {
      root.Vserver = {};
    }
    root.Vserver.GetNetworkInterfaceListRequest = factory(root.Vserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetNetworkInterfaceListRequest model module.
   * @module model/GetNetworkInterfaceListRequest
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>GetNetworkInterfaceListRequest</code>.
   * @alias module:model/GetNetworkInterfaceListRequest
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>GetNetworkInterfaceListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetNetworkInterfaceListRequest} obj Optional instance to populate.
   * @return {module:model/GetNetworkInterfaceListRequest} The populated <code>GetNetworkInterfaceListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('networkInterfaceNoList')) {
        obj['networkInterfaceNoList'] = ApiClient.convertToType(data['networkInterfaceNoList'], ['String']);
      }
      if (data.hasOwnProperty('ip')) {
        obj['ip'] = ApiClient.convertToType(data['ip'], 'String');
      }
      if (data.hasOwnProperty('networkInterfaceName')) {
        obj['networkInterfaceName'] = ApiClient.convertToType(data['networkInterfaceName'], 'String');
      }
      if (data.hasOwnProperty('serverName')) {
        obj['serverName'] = ApiClient.convertToType(data['serverName'], 'String');
      }
      if (data.hasOwnProperty('subnetName')) {
        obj['subnetName'] = ApiClient.convertToType(data['subnetName'], 'String');
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * 네트워크인터페이스번호리스트
   * @member {Array.<String>} networkInterfaceNoList
   */
  exports.prototype['networkInterfaceNoList'] = undefined;
  /**
   * IP주소
   * @member {String} ip
   */
  exports.prototype['ip'] = undefined;
  /**
   * 네트워크인터페이스이름
   * @member {String} networkInterfaceName
   */
  exports.prototype['networkInterfaceName'] = undefined;
  /**
   * 서버이름
   * @member {String} serverName
   */
  exports.prototype['serverName'] = undefined;
  /**
   * 서브넷이름
   * @member {String} subnetName
   */
  exports.prototype['subnetName'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;



  return exports;
}));


