/*
* vserver
* VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vserver) {
      root.Vserver = {};
    }
    root.Vserver.GetPlacementGroupListRequest = factory(root.Vserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetPlacementGroupListRequest model module.
   * @module model/GetPlacementGroupListRequest
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>GetPlacementGroupListRequest</code>.
   * @alias module:model/GetPlacementGroupListRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>GetPlacementGroupListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetPlacementGroupListRequest} obj Optional instance to populate.
   * @return {module:model/GetPlacementGroupListRequest} The populated <code>GetPlacementGroupListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('placementGroupName')) {
        obj['placementGroupName'] = ApiClient.convertToType(data['placementGroupName'], 'String');
      }
      if (data.hasOwnProperty('placementGroupNoList')) {
        obj['placementGroupNoList'] = ApiClient.convertToType(data['placementGroupNoList'], ['String']);
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * 물리배치그룹이름
   * @member {String} placementGroupName
   */
  exports.prototype['placementGroupName'] = undefined;
  /**
   * 물리배치그룹번호리스트
   * @member {Array.<String>} placementGroupNoList
   */
  exports.prototype['placementGroupNoList'] = undefined;



  return exports;
}));


