/*
* vserver
* VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RootPasswordServerInstanceParameter'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RootPasswordServerInstanceParameter'));
  } else {
    // Browser globals (root is window)
    if (!root.Vserver) {
      root.Vserver = {};
    }
    root.Vserver.GetRootPasswordServerInstanceListRequest = factory(root.Vserver.ApiClient, root.Vserver.RootPasswordServerInstanceParameter);
  }
}(this, function(ApiClient, RootPasswordServerInstanceParameter) {
  'use strict';




  /**
   * The GetRootPasswordServerInstanceListRequest model module.
   * @module model/GetRootPasswordServerInstanceListRequest
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>GetRootPasswordServerInstanceListRequest</code>.
   * @alias module:model/GetRootPasswordServerInstanceListRequest
   * @class
   * @param rootPasswordServerInstanceList {Array.<module:model/RootPasswordServerInstanceParameter>} 루트패스워드서버인스턴스리스트
   */
  var exports = function(rootPasswordServerInstanceList) {
    var _this = this;


    _this['rootPasswordServerInstanceList'] = rootPasswordServerInstanceList;
  };

  /**
   * Constructs a <code>GetRootPasswordServerInstanceListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetRootPasswordServerInstanceListRequest} obj Optional instance to populate.
   * @return {module:model/GetRootPasswordServerInstanceListRequest} The populated <code>GetRootPasswordServerInstanceListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('rootPasswordServerInstanceList')) {
        obj['rootPasswordServerInstanceList'] = ApiClient.convertToType(data['rootPasswordServerInstanceList'], [RootPasswordServerInstanceParameter]);
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * 루트패스워드서버인스턴스리스트
   * @member {Array.<module:model/RootPasswordServerInstanceParameter>} rootPasswordServerInstanceList
   */
  exports.prototype['rootPasswordServerInstanceList'] = undefined;



  return exports;
}));


