/*
* vserver
* VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vserver) {
      root.Vserver = {};
    }
    root.Vserver.LoginKey = factory(root.Vserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LoginKey model module.
   * @module model/LoginKey
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>LoginKey</code>.
   * @alias module:model/LoginKey
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>LoginKey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginKey} obj Optional instance to populate.
   * @return {module:model/LoginKey} The populated <code>LoginKey</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('keyName')) {
        obj['keyName'] = ApiClient.convertToType(data['keyName'], 'String');
      }
      if (data.hasOwnProperty('fingerprint')) {
        obj['fingerprint'] = ApiClient.convertToType(data['fingerprint'], 'String');
      }
      if (data.hasOwnProperty('publicKey')) {
        obj['publicKey'] = ApiClient.convertToType(data['publicKey'], 'String');
      }
      if (data.hasOwnProperty('createDate')) {
        obj['createDate'] = ApiClient.convertToType(data['createDate'], 'String');
      }
    }
    return obj;
  }

  /**
   * 키이름
   * @member {String} keyName
   */
  exports.prototype['keyName'] = undefined;
  /**
   * 핑거프린트
   * @member {String} fingerprint
   */
  exports.prototype['fingerprint'] = undefined;
  /**
   * 공개키
   * @member {String} publicKey
   */
  exports.prototype['publicKey'] = undefined;
  /**
   * 생성일시
   * @member {String} createDate
   */
  exports.prototype['createDate'] = undefined;



  return exports;
}));


