/*
* monitoring
* <br/>https://ncloud.apigw.ntruss.com/monitoring/v2
*
* OpenAPI spec version: 2020-05-22T05:53:06Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MetricData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MetricData'));
  } else {
    // Browser globals (root is window)
    if (!root.Monitoring) {
      root.Monitoring = {};
    }
    root.Monitoring.MetricStatistic = factory(root.Monitoring.ApiClient, root.Monitoring.MetricData);
  }
}(this, function(ApiClient, MetricData) {
  'use strict';




  /**
   * The MetricStatistic model module.
   * @module model/MetricStatistic
   * @version 1.4.3
   */

  /**
   * Constructs a new <code>MetricStatistic</code>.
   * @alias module:model/MetricStatistic
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>MetricStatistic</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MetricStatistic} obj Optional instance to populate.
   * @return {module:model/MetricStatistic} The populated <code>MetricStatistic</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('instanceNo')) {
        obj['instanceNo'] = ApiClient.convertToType(data['instanceNo'], 'String');
      }
      if (data.hasOwnProperty('metricDataList')) {
        obj['metricDataList'] = ApiClient.convertToType(data['metricDataList'], [MetricData]);
      }
    }
    return obj;
  }

  /**
   * @member {String} instanceNo
   */
  exports.prototype['instanceNo'] = undefined;
  /**
   * @member {Array.<module:model/MetricData>} metricDataList
   */
  exports.prototype['metricDataList'] = undefined;



  return exports;
}));


