/*
* server
* <br/>https://ncloud.beta-apigw.ntruss.com/server/v1
*
* OpenAPI spec version: 2018-05-30T06:14:49Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.AccessControlGroupRequest = factory(root.Server.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AccessControlGroupRequest model module.
   * @module com.ncloud.server.model/AccessControlGroupRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AccessControlGroupRequest</code>.
   * @alias module:com.ncloud.server.model/AccessControlGroupRequest
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>AccessControlGroupRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.server.model/AccessControlGroupRequest} obj Optional instance to populate.
   * @return {module:com.ncloud.server.model/AccessControlGroupRequest} The populated <code>AccessControlGroupRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accessControlGroupConfigurationNoList')) {
        obj['accessControlGroupConfigurationNoList'] = ApiClient.convertToType(data['accessControlGroupConfigurationNoList'], ['String']);
      }
      if (data.hasOwnProperty('isDefault')) {
        obj['isDefault'] = ApiClient.convertToType(data['isDefault'], 'Boolean');
      }
      if (data.hasOwnProperty('accessControlGroupName')) {
        obj['accessControlGroupName'] = ApiClient.convertToType(data['accessControlGroupName'], 'String');
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('responseFormatType')) {
        obj['responseFormatType'] = ApiClient.convertToType(data['responseFormatType'], 'String');
      }
    }
    return obj;
  }

  /**
   * 접근제어그룹설정번호리스트
   * @member {Array.<String>} accessControlGroupConfigurationNoList
   */
  exports.prototype['accessControlGroupConfigurationNoList'] = undefined;
  /**
   * 디폴트여부
   * @member {Boolean} isDefault
   */
  exports.prototype['isDefault'] = undefined;
  /**
   * 접근제어그룹명
   * @member {String} accessControlGroupName
   */
  exports.prototype['accessControlGroupName'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * responseFormatType {json, xml}
   * @member {String} responseFormatType
   */
  exports.prototype['responseFormatType'] = undefined;



  return exports;
}));


