/*
* server
* <br/>https://ncloud.beta-apigw.ntruss.com/server/v1
*
* OpenAPI spec version: 2018-05-30T06:14:49Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.ncloud.server.model/CommonCode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CommonCode'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.BlockStorageSnapshotInstance = factory(root.Server.ApiClient, root.Server.CommonCode);
  }
}(this, function(ApiClient, CommonCode) {
  'use strict';




  /**
   * The BlockStorageSnapshotInstance model module.
   * @module com.ncloud.server.model/BlockStorageSnapshotInstance
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>BlockStorageSnapshotInstance</code>.
   * @alias module:com.ncloud.server.model/BlockStorageSnapshotInstance
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>BlockStorageSnapshotInstance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.server.model/BlockStorageSnapshotInstance} obj Optional instance to populate.
   * @return {module:com.ncloud.server.model/BlockStorageSnapshotInstance} The populated <code>BlockStorageSnapshotInstance</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('blockStorageSnapshotInstanceNo')) {
        obj['blockStorageSnapshotInstanceNo'] = ApiClient.convertToType(data['blockStorageSnapshotInstanceNo'], 'String');
      }
      if (data.hasOwnProperty('blockStorageSnapshotName')) {
        obj['blockStorageSnapshotName'] = ApiClient.convertToType(data['blockStorageSnapshotName'], 'String');
      }
      if (data.hasOwnProperty('blockStorageSnapshotVolumeSize')) {
        obj['blockStorageSnapshotVolumeSize'] = ApiClient.convertToType(data['blockStorageSnapshotVolumeSize'], 'Number');
      }
      if (data.hasOwnProperty('originalBlockStorageInstanceNo')) {
        obj['originalBlockStorageInstanceNo'] = ApiClient.convertToType(data['originalBlockStorageInstanceNo'], 'String');
      }
      if (data.hasOwnProperty('originalBlockStorageName')) {
        obj['originalBlockStorageName'] = ApiClient.convertToType(data['originalBlockStorageName'], 'String');
      }
      if (data.hasOwnProperty('blockStorageSnapshotInstanceStatus')) {
        obj['blockStorageSnapshotInstanceStatus'] = CommonCode.constructFromObject(data['blockStorageSnapshotInstanceStatus']);
      }
      if (data.hasOwnProperty('blockStorageSnapshotInstanceOperation')) {
        obj['blockStorageSnapshotInstanceOperation'] = CommonCode.constructFromObject(data['blockStorageSnapshotInstanceOperation']);
      }
      if (data.hasOwnProperty('blockStorageSnapshotInstanceStatusName')) {
        obj['blockStorageSnapshotInstanceStatusName'] = ApiClient.convertToType(data['blockStorageSnapshotInstanceStatusName'], 'String');
      }
      if (data.hasOwnProperty('createDate')) {
        obj['createDate'] = ApiClient.convertToType(data['createDate'], 'String');
      }
      if (data.hasOwnProperty('blockStorageSnapshotInstanceDescription')) {
        obj['blockStorageSnapshotInstanceDescription'] = ApiClient.convertToType(data['blockStorageSnapshotInstanceDescription'], 'String');
      }
      if (data.hasOwnProperty('serverImageProductCode')) {
        obj['serverImageProductCode'] = ApiClient.convertToType(data['serverImageProductCode'], 'String');
      }
      if (data.hasOwnProperty('osInformation')) {
        obj['osInformation'] = ApiClient.convertToType(data['osInformation'], 'String');
      }
    }
    return obj;
  }

  /**
   * 블록스토리지스냅샷인스턴스번호
   * @member {String} blockStorageSnapshotInstanceNo
   */
  exports.prototype['blockStorageSnapshotInstanceNo'] = undefined;
  /**
   * 블록스토리지스냅샷명
   * @member {String} blockStorageSnapshotName
   */
  exports.prototype['blockStorageSnapshotName'] = undefined;
  /**
   * 블록스토지리볼륨사이즈
   * @member {Number} blockStorageSnapshotVolumeSize
   */
  exports.prototype['blockStorageSnapshotVolumeSize'] = undefined;
  /**
   * 원본블록스토리지인스턴스번호
   * @member {String} originalBlockStorageInstanceNo
   */
  exports.prototype['originalBlockStorageInstanceNo'] = undefined;
  /**
   * 원본블록스토리지명
   * @member {String} originalBlockStorageName
   */
  exports.prototype['originalBlockStorageName'] = undefined;
  /**
   * 블록스토리지스냅샷인스턴스상태
   * @member {module:com.ncloud.server.model/CommonCode} blockStorageSnapshotInstanceStatus
   */
  exports.prototype['blockStorageSnapshotInstanceStatus'] = undefined;
  /**
   * 블록스토리지스냅샷인스턴스OP
   * @member {module:com.ncloud.server.model/CommonCode} blockStorageSnapshotInstanceOperation
   */
  exports.prototype['blockStorageSnapshotInstanceOperation'] = undefined;
  /**
   * @member {String} blockStorageSnapshotInstanceStatusName
   */
  exports.prototype['blockStorageSnapshotInstanceStatusName'] = undefined;
  /**
   * 생성일시
   * @member {String} createDate
   */
  exports.prototype['createDate'] = undefined;
  /**
   * 블록스토리지스냅샷인스턴스설명
   * @member {String} blockStorageSnapshotInstanceDescription
   */
  exports.prototype['blockStorageSnapshotInstanceDescription'] = undefined;
  /**
   * 서버이미지상품코드
   * @member {String} serverImageProductCode
   */
  exports.prototype['serverImageProductCode'] = undefined;
  /**
   * OS정보
   * @member {String} osInformation
   */
  exports.prototype['osInformation'] = undefined;



  return exports;
}));


