/*
* server
* <br/>https://ncloud.beta-apigw.ntruss.com/server/v1
*
* OpenAPI spec version: 2018-05-30T06:14:49Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.GetNasVolumeInstanceRatingListRequest = factory(root.Server.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetNasVolumeInstanceRatingListRequest model module.
   * @module com.ncloud.server.model/GetNasVolumeInstanceRatingListRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetNasVolumeInstanceRatingListRequest</code>.
   * @alias module:com.ncloud.server.model/GetNasVolumeInstanceRatingListRequest
   * @class
   * @param endTime {String} 측정종료시간
   * @param interval {String} 측정간격
   * @param nasVolumeInstanceNo {String} NAS볼륨인스턴스번호
   * @param startTime {String} 측정시작시간
   */
  var exports = function(endTime, interval, nasVolumeInstanceNo, startTime) {
    var _this = this;

    _this['endTime'] = endTime;
    _this['interval'] = interval;
    _this['nasVolumeInstanceNo'] = nasVolumeInstanceNo;
    _this['startTime'] = startTime;

  };

  /**
   * Constructs a <code>GetNasVolumeInstanceRatingListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.server.model/GetNasVolumeInstanceRatingListRequest} obj Optional instance to populate.
   * @return {module:com.ncloud.server.model/GetNasVolumeInstanceRatingListRequest} The populated <code>GetNasVolumeInstanceRatingListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('endTime')) {
        obj['endTime'] = ApiClient.convertToType(data['endTime'], 'String');
      }
      if (data.hasOwnProperty('interval')) {
        obj['interval'] = ApiClient.convertToType(data['interval'], 'String');
      }
      if (data.hasOwnProperty('nasVolumeInstanceNo')) {
        obj['nasVolumeInstanceNo'] = ApiClient.convertToType(data['nasVolumeInstanceNo'], 'String');
      }
      if (data.hasOwnProperty('startTime')) {
        obj['startTime'] = ApiClient.convertToType(data['startTime'], 'String');
      }
      if (data.hasOwnProperty('responseFormatType')) {
        obj['responseFormatType'] = ApiClient.convertToType(data['responseFormatType'], 'String');
      }
    }
    return obj;
  }

  /**
   * 측정종료시간
   * @member {String} endTime
   */
  exports.prototype['endTime'] = undefined;
  /**
   * 측정간격
   * @member {String} interval
   */
  exports.prototype['interval'] = undefined;
  /**
   * NAS볼륨인스턴스번호
   * @member {String} nasVolumeInstanceNo
   */
  exports.prototype['nasVolumeInstanceNo'] = undefined;
  /**
   * 측정시작시간
   * @member {String} startTime
   */
  exports.prototype['startTime'] = undefined;
  /**
   * responseFormatType {json, xml}
   * @member {String} responseFormatType
   */
  exports.prototype['responseFormatType'] = undefined;



  return exports;
}));


