/*
* server
* <br/>https://ncloud.beta-apigw.ntruss.com/server/v1
*
* OpenAPI spec version: 2018-05-30T06:14:49Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.GetServerImageProductListRequest = factory(root.Server.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetServerImageProductListRequest model module.
   * @module com.ncloud.server.model/GetServerImageProductListRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetServerImageProductListRequest</code>.
   * @alias module:com.ncloud.server.model/GetServerImageProductListRequest
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>GetServerImageProductListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.server.model/GetServerImageProductListRequest} obj Optional instance to populate.
   * @return {module:com.ncloud.server.model/GetServerImageProductListRequest} The populated <code>GetServerImageProductListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('exclusionProductCode')) {
        obj['exclusionProductCode'] = ApiClient.convertToType(data['exclusionProductCode'], 'String');
      }
      if (data.hasOwnProperty('productCode')) {
        obj['productCode'] = ApiClient.convertToType(data['productCode'], 'String');
      }
      if (data.hasOwnProperty('platformTypeCodeList')) {
        obj['platformTypeCodeList'] = ApiClient.convertToType(data['platformTypeCodeList'], ['String']);
      }
      if (data.hasOwnProperty('blockStorageSize')) {
        obj['blockStorageSize'] = ApiClient.convertToType(data['blockStorageSize'], 'Number');
      }
      if (data.hasOwnProperty('regionNo')) {
        obj['regionNo'] = ApiClient.convertToType(data['regionNo'], 'String');
      }
      if (data.hasOwnProperty('infraResourceDetailTypeCode')) {
        obj['infraResourceDetailTypeCode'] = ApiClient.convertToType(data['infraResourceDetailTypeCode'], 'String');
      }
      if (data.hasOwnProperty('responseFormatType')) {
        obj['responseFormatType'] = ApiClient.convertToType(data['responseFormatType'], 'String');
      }
    }
    return obj;
  }

  /**
   * 제외할상품코드
   * @member {String} exclusionProductCode
   */
  exports.prototype['exclusionProductCode'] = undefined;
  /**
   * 조회할상품코드
   * @member {String} productCode
   */
  exports.prototype['productCode'] = undefined;
  /**
   * 플랫폼유형코드리스트
   * @member {Array.<String>} platformTypeCodeList
   */
  exports.prototype['platformTypeCodeList'] = undefined;
  /**
   * 블록스토리지사이즈
   * @member {Number} blockStorageSize
   */
  exports.prototype['blockStorageSize'] = undefined;
  /**
   * 리전번호
   * @member {String} regionNo
   */
  exports.prototype['regionNo'] = undefined;
  /**
   * 인프라자원상세구분코드
   * @member {String} infraResourceDetailTypeCode
   */
  exports.prototype['infraResourceDetailTypeCode'] = undefined;
  /**
   * responseFormatType {json, xml}
   * @member {String} responseFormatType
   */
  exports.prototype['responseFormatType'] = undefined;



  return exports;
}));


