/*
* server
* <br/>https://ncloud.beta-apigw.ntruss.com/server/v1
*
* OpenAPI spec version: 2018-05-30T06:14:49Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.PublicIpInstanceNoList = factory(root.Server.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PublicIpInstanceNoList model module.
   * @module com.ncloud.server.model/PublicIpInstanceNoList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PublicIpInstanceNoList</code>.
   * @alias module:com.ncloud.server.model/PublicIpInstanceNoList
   * @class
   * @param publicIpInstanceNoList {Array.<String>} 공인IP인스턴스번호리스트
   */
  var exports = function(publicIpInstanceNoList) {
    var _this = this;

    _this['publicIpInstanceNoList'] = publicIpInstanceNoList;

  };

  /**
   * Constructs a <code>PublicIpInstanceNoList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.server.model/PublicIpInstanceNoList} obj Optional instance to populate.
   * @return {module:com.ncloud.server.model/PublicIpInstanceNoList} The populated <code>PublicIpInstanceNoList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('publicIpInstanceNoList')) {
        obj['publicIpInstanceNoList'] = ApiClient.convertToType(data['publicIpInstanceNoList'], ['String']);
      }
      if (data.hasOwnProperty('responseFormatType')) {
        obj['responseFormatType'] = ApiClient.convertToType(data['responseFormatType'], 'String');
      }
    }
    return obj;
  }

  /**
   * 공인IP인스턴스번호리스트
   * @member {Array.<String>} publicIpInstanceNoList
   */
  exports.prototype['publicIpInstanceNoList'] = undefined;
  /**
   * responseFormatType {json, xml}
   * @member {String} responseFormatType
   */
  exports.prototype['responseFormatType'] = undefined;



  return exports;
}));


