/*
* cdn
* <br/>https://ncloud.beta-apigw.ntruss.com/cdn/v2
*
* OpenAPI spec version: 2018-06-20T07:18:23Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cdn) {
      root.Cdn = {};
    }
    root.Cdn.RequestCdnPlusPurgeRequest = factory(root.Cdn.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RequestCdnPlusPurgeRequest model module.
   * @module com.ncloud.cdn.model/RequestCdnPlusPurgeRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RequestCdnPlusPurgeRequest</code>.
   * @alias module:com.ncloud.cdn.model/RequestCdnPlusPurgeRequest
   * @class
   * @param cdnInstanceNo {String} CDN인스턴스번호
   * @param isWholePurge {Boolean} 전체퍼지여부
   * @param isWholeDomain {Boolean} 전체도메인여부
   */
  var exports = function(cdnInstanceNo, isWholePurge, isWholeDomain) {
    var _this = this;

    _this['cdnInstanceNo'] = cdnInstanceNo;

    _this['isWholePurge'] = isWholePurge;
    _this['isWholeDomain'] = isWholeDomain;



  };

  /**
   * Constructs a <code>RequestCdnPlusPurgeRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.cdn.model/RequestCdnPlusPurgeRequest} obj Optional instance to populate.
   * @return {module:com.ncloud.cdn.model/RequestCdnPlusPurgeRequest} The populated <code>RequestCdnPlusPurgeRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('cdnInstanceNo')) {
        obj['cdnInstanceNo'] = ApiClient.convertToType(data['cdnInstanceNo'], 'String');
      }
      if (data.hasOwnProperty('domainIdList')) {
        obj['domainIdList'] = ApiClient.convertToType(data['domainIdList'], ['String']);
      }
      if (data.hasOwnProperty('isWholePurge')) {
        obj['isWholePurge'] = ApiClient.convertToType(data['isWholePurge'], 'Boolean');
      }
      if (data.hasOwnProperty('isWholeDomain')) {
        obj['isWholeDomain'] = ApiClient.convertToType(data['isWholeDomain'], 'Boolean');
      }
      if (data.hasOwnProperty('targetFileList')) {
        obj['targetFileList'] = ApiClient.convertToType(data['targetFileList'], ['String']);
      }
      if (data.hasOwnProperty('targetDirectoryName')) {
        obj['targetDirectoryName'] = ApiClient.convertToType(data['targetDirectoryName'], 'String');
      }
      if (data.hasOwnProperty('responseFormatType')) {
        obj['responseFormatType'] = ApiClient.convertToType(data['responseFormatType'], 'String');
      }
    }
    return obj;
  }

  /**
   * CDN인스턴스번호
   * @member {String} cdnInstanceNo
   */
  exports.prototype['cdnInstanceNo'] = undefined;
  /**
   * 도메인ID리스트
   * @member {Array.<String>} domainIdList
   */
  exports.prototype['domainIdList'] = undefined;
  /**
   * 전체퍼지여부
   * @member {Boolean} isWholePurge
   */
  exports.prototype['isWholePurge'] = undefined;
  /**
   * 전체도메인여부
   * @member {Boolean} isWholeDomain
   */
  exports.prototype['isWholeDomain'] = undefined;
  /**
   * 대상파일리스트
   * @member {Array.<String>} targetFileList
   */
  exports.prototype['targetFileList'] = undefined;
  /**
   * 대상디렉토리명
   * @member {String} targetDirectoryName
   */
  exports.prototype['targetDirectoryName'] = undefined;
  /**
   * responseFormatType {json, xml}
   * @member {String} responseFormatType
   */
  exports.prototype['responseFormatType'] = undefined;



  return exports;
}));


