/*
* autoscaling
* <br/>https://ncloud.apigw.ntruss.com/autoscaling/v2
*
* OpenAPI spec version: 2018-06-21T02:22:22Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccessControlGroup'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccessControlGroup'));
  } else {
    // Browser globals (root is window)
    if (!root.Autoscaling) {
      root.Autoscaling = {};
    }
    root.Autoscaling.LaunchConfiguration = factory(root.Autoscaling.ApiClient, root.Autoscaling.AccessControlGroup);
  }
}(this, function(ApiClient, AccessControlGroup) {
  'use strict';




  /**
   * The LaunchConfiguration model module.
   * @module model/LaunchConfiguration
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>LaunchConfiguration</code>.
   * @alias module:model/LaunchConfiguration
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>LaunchConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LaunchConfiguration} obj Optional instance to populate.
   * @return {module:model/LaunchConfiguration} The populated <code>LaunchConfiguration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('launchConfigurationName')) {
        obj['launchConfigurationName'] = ApiClient.convertToType(data['launchConfigurationName'], 'String');
      }
      if (data.hasOwnProperty('serverImageProductCode')) {
        obj['serverImageProductCode'] = ApiClient.convertToType(data['serverImageProductCode'], 'String');
      }
      if (data.hasOwnProperty('serverProductCode')) {
        obj['serverProductCode'] = ApiClient.convertToType(data['serverProductCode'], 'String');
      }
      if (data.hasOwnProperty('memberServerImageNo')) {
        obj['memberServerImageNo'] = ApiClient.convertToType(data['memberServerImageNo'], 'String');
      }
      if (data.hasOwnProperty('loginKeyName')) {
        obj['loginKeyName'] = ApiClient.convertToType(data['loginKeyName'], 'String');
      }
      if (data.hasOwnProperty('createDate')) {
        obj['createDate'] = ApiClient.convertToType(data['createDate'], 'String');
      }
      if (data.hasOwnProperty('userData')) {
        obj['userData'] = ApiClient.convertToType(data['userData'], 'String');
      }
      if (data.hasOwnProperty('accessControlGroupList')) {
        obj['accessControlGroupList'] = ApiClient.convertToType(data['accessControlGroupList'], [AccessControlGroup]);
      }
    }
    return obj;
  }

  /**
   * 론치설정명
   * @member {String} launchConfigurationName
   */
  exports.prototype['launchConfigurationName'] = undefined;
  /**
   * 서버이미지상품코드
   * @member {String} serverImageProductCode
   */
  exports.prototype['serverImageProductCode'] = undefined;
  /**
   * 서버상품코드
   * @member {String} serverProductCode
   */
  exports.prototype['serverProductCode'] = undefined;
  /**
   * 회원서버이미지번호
   * @member {String} memberServerImageNo
   */
  exports.prototype['memberServerImageNo'] = undefined;
  /**
   * 로그인키명
   * @member {String} loginKeyName
   */
  exports.prototype['loginKeyName'] = undefined;
  /**
   * 생성일시
   * @member {String} createDate
   */
  exports.prototype['createDate'] = undefined;
  /**
   * 사용자데이터
   * @member {String} userData
   */
  exports.prototype['userData'] = undefined;
  /**
   * ACG리스트
   * @member {Array.<module:model/AccessControlGroup>} accessControlGroupList
   */
  exports.prototype['accessControlGroupList'] = undefined;



  return exports;
}));


