/*
* server
* <br/>https://ncloud.apigw.ntruss.com/server/v2
*
* OpenAPI spec version: 2019-01-25T05:09:58Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CommonCode', 'model/PortForwardingRule', 'model/Zone'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CommonCode'), require('./PortForwardingRule'), require('./Zone'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.AddPortForwardingRulesResponse = factory(root.Server.ApiClient, root.Server.CommonCode, root.Server.PortForwardingRule, root.Server.Zone);
  }
}(this, function(ApiClient, CommonCode, PortForwardingRule, Zone) {
  'use strict';




  /**
   * The AddPortForwardingRulesResponse model module.
   * @module model/AddPortForwardingRulesResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AddPortForwardingRulesResponse</code>.
   * @alias module:model/AddPortForwardingRulesResponse
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>AddPortForwardingRulesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddPortForwardingRulesResponse} obj Optional instance to populate.
   * @return {module:model/AddPortForwardingRulesResponse} The populated <code>AddPortForwardingRulesResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('requestId')) {
        obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
      }
      if (data.hasOwnProperty('returnCode')) {
        obj['returnCode'] = ApiClient.convertToType(data['returnCode'], 'String');
      }
      if (data.hasOwnProperty('returnMessage')) {
        obj['returnMessage'] = ApiClient.convertToType(data['returnMessage'], 'String');
      }
      if (data.hasOwnProperty('portForwardingConfigurationNo')) {
        obj['portForwardingConfigurationNo'] = ApiClient.convertToType(data['portForwardingConfigurationNo'], 'String');
      }
      if (data.hasOwnProperty('portForwardingPublicIp')) {
        obj['portForwardingPublicIp'] = ApiClient.convertToType(data['portForwardingPublicIp'], 'String');
      }
      if (data.hasOwnProperty('zone')) {
        obj['zone'] = Zone.constructFromObject(data['zone']);
      }
      if (data.hasOwnProperty('internetLineType')) {
        obj['internetLineType'] = CommonCode.constructFromObject(data['internetLineType']);
      }
      if (data.hasOwnProperty('totalRows')) {
        obj['totalRows'] = ApiClient.convertToType(data['totalRows'], 'Number');
      }
      if (data.hasOwnProperty('portForwardingRuleList')) {
        obj['portForwardingRuleList'] = ApiClient.convertToType(data['portForwardingRuleList'], [PortForwardingRule]);
      }
    }
    return obj;
  }

  /**
   * @member {String} requestId
   */
  exports.prototype['requestId'] = undefined;
  /**
   * @member {String} returnCode
   */
  exports.prototype['returnCode'] = undefined;
  /**
   * @member {String} returnMessage
   */
  exports.prototype['returnMessage'] = undefined;
  /**
   * 포트포워딩설정번호
   * @member {String} portForwardingConfigurationNo
   */
  exports.prototype['portForwardingConfigurationNo'] = undefined;
  /**
   * 포트포워딩공인IP
   * @member {String} portForwardingPublicIp
   */
  exports.prototype['portForwardingPublicIp'] = undefined;
  /**
   * ZONE
   * @member {module:model/Zone} zone
   */
  exports.prototype['zone'] = undefined;
  /**
   * 인터넷회선구분
   * @member {module:model/CommonCode} internetLineType
   */
  exports.prototype['internetLineType'] = undefined;
  /**
   * @member {Number} totalRows
   */
  exports.prototype['totalRows'] = undefined;
  /**
   * @member {Array.<module:model/PortForwardingRule>} portForwardingRuleList
   */
  exports.prototype['portForwardingRuleList'] = undefined;



  return exports;
}));


