/*
* server
* <br/>https://ncloud.apigw.ntruss.com/server/v2
*
* OpenAPI spec version: 2018-07-02T09:06:17Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.CreateNasVolumeInstanceRequest = factory(root.Server.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreateNasVolumeInstanceRequest model module.
   * @module model/CreateNasVolumeInstanceRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CreateNasVolumeInstanceRequest</code>.
   * @alias module:model/CreateNasVolumeInstanceRequest
   * @class
   * @param volumeName {String} 볼륨이름
   * @param volumeSize {Number} NAS볼륨사이즈
   * @param volumeAllotmentProtocolTypeCode {String} 볼륨할당프로토콜유형코드
   */
  var exports = function(volumeName, volumeSize, volumeAllotmentProtocolTypeCode) {
    var _this = this;

    _this['volumeName'] = volumeName;
    _this['volumeSize'] = volumeSize;
    _this['volumeAllotmentProtocolTypeCode'] = volumeAllotmentProtocolTypeCode;







  };

  /**
   * Constructs a <code>CreateNasVolumeInstanceRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateNasVolumeInstanceRequest} obj Optional instance to populate.
   * @return {module:model/CreateNasVolumeInstanceRequest} The populated <code>CreateNasVolumeInstanceRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('volumeName')) {
        obj['volumeName'] = ApiClient.convertToType(data['volumeName'], 'String');
      }
      if (data.hasOwnProperty('volumeSize')) {
        obj['volumeSize'] = ApiClient.convertToType(data['volumeSize'], 'Number');
      }
      if (data.hasOwnProperty('volumeAllotmentProtocolTypeCode')) {
        obj['volumeAllotmentProtocolTypeCode'] = ApiClient.convertToType(data['volumeAllotmentProtocolTypeCode'], 'String');
      }
      if (data.hasOwnProperty('serverInstanceNoList')) {
        obj['serverInstanceNoList'] = ApiClient.convertToType(data['serverInstanceNoList'], ['String']);
      }
      if (data.hasOwnProperty('customIpList')) {
        obj['customIpList'] = ApiClient.convertToType(data['customIpList'], ['String']);
      }
      if (data.hasOwnProperty('cifsUserName')) {
        obj['cifsUserName'] = ApiClient.convertToType(data['cifsUserName'], 'String');
      }
      if (data.hasOwnProperty('cifsUserPassword')) {
        obj['cifsUserPassword'] = ApiClient.convertToType(data['cifsUserPassword'], 'String');
      }
      if (data.hasOwnProperty('nasVolumeDescription')) {
        obj['nasVolumeDescription'] = ApiClient.convertToType(data['nasVolumeDescription'], 'String');
      }
      if (data.hasOwnProperty('regionNo')) {
        obj['regionNo'] = ApiClient.convertToType(data['regionNo'], 'String');
      }
      if (data.hasOwnProperty('zoneNo')) {
        obj['zoneNo'] = ApiClient.convertToType(data['zoneNo'], 'String');
      }
    }
    return obj;
  }

  /**
   * 볼륨이름
   * @member {String} volumeName
   */
  exports.prototype['volumeName'] = undefined;
  /**
   * NAS볼륨사이즈
   * @member {Number} volumeSize
   */
  exports.prototype['volumeSize'] = undefined;
  /**
   * 볼륨할당프로토콜유형코드
   * @member {String} volumeAllotmentProtocolTypeCode
   */
  exports.prototype['volumeAllotmentProtocolTypeCode'] = undefined;
  /**
   * 서버인스턴스번호리스트
   * @member {Array.<String>} serverInstanceNoList
   */
  exports.prototype['serverInstanceNoList'] = undefined;
  /**
   * 커스텀IP리스트
   * @member {Array.<String>} customIpList
   */
  exports.prototype['customIpList'] = undefined;
  /**
   * CIFS유저이름
   * @member {String} cifsUserName
   */
  exports.prototype['cifsUserName'] = undefined;
  /**
   * CIFS유저비밀번호
   * @member {String} cifsUserPassword
   */
  exports.prototype['cifsUserPassword'] = undefined;
  /**
   * NAS볼륨설명
   * @member {String} nasVolumeDescription
   */
  exports.prototype['nasVolumeDescription'] = undefined;
  /**
   * 리전번호
   * @member {String} regionNo
   */
  exports.prototype['regionNo'] = undefined;
  /**
   * ZONE번호
   * @member {String} zoneNo
   */
  exports.prototype['zoneNo'] = undefined;



  return exports;
}));


