/*
* server
* <br/>https://ncloud.apigw.ntruss.com/server/v2
*
* OpenAPI spec version: 2019-10-17T10:28:43Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.DeleteNetworkInterfaceRequest = factory(root.Server.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeleteNetworkInterfaceRequest model module.
   * @module model/DeleteNetworkInterfaceRequest
   * @version 1.4.1
   */

  /**
   * Constructs a new <code>DeleteNetworkInterfaceRequest</code>.
   * @alias module:model/DeleteNetworkInterfaceRequest
   * @class
   * @param networkInterfaceNo {String} Network Interface번호
   */
  var exports = function(networkInterfaceNo) {
    var _this = this;

    _this['networkInterfaceNo'] = networkInterfaceNo;
  };

  /**
   * Constructs a <code>DeleteNetworkInterfaceRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeleteNetworkInterfaceRequest} obj Optional instance to populate.
   * @return {module:model/DeleteNetworkInterfaceRequest} The populated <code>DeleteNetworkInterfaceRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('networkInterfaceNo')) {
        obj['networkInterfaceNo'] = ApiClient.convertToType(data['networkInterfaceNo'], 'String');
      }
    }
    return obj;
  }

  /**
   * Network Interface번호
   * @member {String} networkInterfaceNo
   */
  exports.prototype['networkInterfaceNo'] = undefined;



  return exports;
}));


