/*
* server
* <br/>https://ncloud.apigw.ntruss.com/server/v2
*
* OpenAPI spec version: 2019-01-25T05:09:58Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.DetachBlockStorageInstancesRequest = factory(root.Server.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DetachBlockStorageInstancesRequest model module.
   * @module model/DetachBlockStorageInstancesRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DetachBlockStorageInstancesRequest</code>.
   * @alias module:model/DetachBlockStorageInstancesRequest
   * @class
   * @param blockStorageInstanceNoList {Array.<String>} 블록스토리지인스턴스번호리스트
   */
  var exports = function(blockStorageInstanceNoList) {
    var _this = this;

    _this['blockStorageInstanceNoList'] = blockStorageInstanceNoList;
  };

  /**
   * Constructs a <code>DetachBlockStorageInstancesRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DetachBlockStorageInstancesRequest} obj Optional instance to populate.
   * @return {module:model/DetachBlockStorageInstancesRequest} The populated <code>DetachBlockStorageInstancesRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('blockStorageInstanceNoList')) {
        obj['blockStorageInstanceNoList'] = ApiClient.convertToType(data['blockStorageInstanceNoList'], ['String']);
      }
    }
    return obj;
  }

  /**
   * 블록스토리지인스턴스번호리스트
   * @member {Array.<String>} blockStorageInstanceNoList
   */
  exports.prototype['blockStorageInstanceNoList'] = undefined;



  return exports;
}));


