/*
* server
* <br/>https://ncloud.apigw.ntruss.com/server/v2
*
* OpenAPI spec version: 2018-07-02T09:06:17Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.GetBlockStorageSnapshotInstanceListRequest = factory(root.Server.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetBlockStorageSnapshotInstanceListRequest model module.
   * @module model/GetBlockStorageSnapshotInstanceListRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetBlockStorageSnapshotInstanceListRequest</code>.
   * @alias module:model/GetBlockStorageSnapshotInstanceListRequest
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>GetBlockStorageSnapshotInstanceListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetBlockStorageSnapshotInstanceListRequest} obj Optional instance to populate.
   * @return {module:model/GetBlockStorageSnapshotInstanceListRequest} The populated <code>GetBlockStorageSnapshotInstanceListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('blockStorageSnapshotInstanceNoList')) {
        obj['blockStorageSnapshotInstanceNoList'] = ApiClient.convertToType(data['blockStorageSnapshotInstanceNoList'], ['String']);
      }
      if (data.hasOwnProperty('originalBlockStorageInstanceNoList')) {
        obj['originalBlockStorageInstanceNoList'] = ApiClient.convertToType(data['originalBlockStorageInstanceNoList'], ['String']);
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('regionNo')) {
        obj['regionNo'] = ApiClient.convertToType(data['regionNo'], 'String');
      }
    }
    return obj;
  }

  /**
   * 블록스토리지스냅샷인스턴스번호리스트
   * @member {Array.<String>} blockStorageSnapshotInstanceNoList
   */
  exports.prototype['blockStorageSnapshotInstanceNoList'] = undefined;
  /**
   * 원본블록스토리지인스턴스번호리스트
   * @member {Array.<String>} originalBlockStorageInstanceNoList
   */
  exports.prototype['originalBlockStorageInstanceNoList'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * 리전번호
   * @member {String} regionNo
   */
  exports.prototype['regionNo'] = undefined;



  return exports;
}));


