/*
* server
* <br/>https://ncloud.apigw.ntruss.com/server/v2
*
* OpenAPI spec version: 2019-10-17T10:28:43Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.GetInstanceTagListRequest = factory(root.Server.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetInstanceTagListRequest model module.
   * @module model/GetInstanceTagListRequest
   * @version 1.4.1
   */

  /**
   * Constructs a new <code>GetInstanceTagListRequest</code>.
   * @alias module:model/GetInstanceTagListRequest
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>GetInstanceTagListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetInstanceTagListRequest} obj Optional instance to populate.
   * @return {module:model/GetInstanceTagListRequest} The populated <code>GetInstanceTagListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('instanceNoList')) {
        obj['instanceNoList'] = ApiClient.convertToType(data['instanceNoList'], ['String']);
      }
      if (data.hasOwnProperty('tagKeyList')) {
        obj['tagKeyList'] = ApiClient.convertToType(data['tagKeyList'], ['String']);
      }
      if (data.hasOwnProperty('tagValueList')) {
        obj['tagValueList'] = ApiClient.convertToType(data['tagValueList'], ['String']);
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 인스턴스번호리스트
   * @member {Array.<String>} instanceNoList
   */
  exports.prototype['instanceNoList'] = undefined;
  /**
   * 태그키리스트
   * @member {Array.<String>} tagKeyList
   */
  exports.prototype['tagKeyList'] = undefined;
  /**
   * 태그값리스트
   * @member {Array.<String>} tagValueList
   */
  exports.prototype['tagValueList'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;



  return exports;
}));


