/*
* server
* <br/>https://ncloud.apigw.ntruss.com/server/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.GetMemberServerImageListRequest = factory(root.Server.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetMemberServerImageListRequest model module.
   * @module model/GetMemberServerImageListRequest
   * @version 1.4.8
   */

  /**
   * Constructs a new <code>GetMemberServerImageListRequest</code>.
   * @alias module:model/GetMemberServerImageListRequest
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>GetMemberServerImageListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetMemberServerImageListRequest} obj Optional instance to populate.
   * @return {module:model/GetMemberServerImageListRequest} The populated <code>GetMemberServerImageListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('memberServerImageNoList')) {
        obj['memberServerImageNoList'] = ApiClient.convertToType(data['memberServerImageNoList'], ['String']);
      }
      if (data.hasOwnProperty('platformTypeCodeList')) {
        obj['platformTypeCodeList'] = ApiClient.convertToType(data['platformTypeCodeList'], ['String']);
      }
      if (data.hasOwnProperty('pageNo')) {
        obj['pageNo'] = ApiClient.convertToType(data['pageNo'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('regionNo')) {
        obj['regionNo'] = ApiClient.convertToType(data['regionNo'], 'String');
      }
      if (data.hasOwnProperty('sortedBy')) {
        obj['sortedBy'] = ApiClient.convertToType(data['sortedBy'], 'String');
      }
      if (data.hasOwnProperty('sortingOrder')) {
        obj['sortingOrder'] = ApiClient.convertToType(data['sortingOrder'], 'String');
      }
    }
    return obj;
  }

  /**
   * 회원서버이미지번호리스트
   * @member {Array.<String>} memberServerImageNoList
   */
  exports.prototype['memberServerImageNoList'] = undefined;
  /**
   * 플랫폼타입코드리스트
   * @member {Array.<String>} platformTypeCodeList
   */
  exports.prototype['platformTypeCodeList'] = undefined;
  /**
   * 페이지번호
   * @member {Number} pageNo
   */
  exports.prototype['pageNo'] = undefined;
  /**
   * 페이지사이즈
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * 리전번호
   * @member {String} regionNo
   */
  exports.prototype['regionNo'] = undefined;
  /**
   * 소팅대상
   * @member {String} sortedBy
   */
  exports.prototype['sortedBy'] = undefined;
  /**
   * 소팅순서
   * @member {String} sortingOrder
   */
  exports.prototype['sortingOrder'] = undefined;



  return exports;
}));


