/*
* server
* <br/>https://ncloud.apigw.ntruss.com/server/v2
*
* OpenAPI spec version: 2019-01-25T05:09:58Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Region', 'model/Zone'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Region'), require('./Zone'));
  } else {
    // Browser globals (root is window)
    if (!root.Server) {
      root.Server = {};
    }
    root.Server.NetworkInterface = factory(root.Server.ApiClient, root.Server.Region, root.Server.Zone);
  }
}(this, function(ApiClient, Region, Zone) {
  'use strict';




  /**
   * The NetworkInterface model module.
   * @module model/NetworkInterface
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>NetworkInterface</code>.
   * @alias module:model/NetworkInterface
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>NetworkInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NetworkInterface} obj Optional instance to populate.
   * @return {module:model/NetworkInterface} The populated <code>NetworkInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('networkInterfaceNo')) {
        obj['networkInterfaceNo'] = ApiClient.convertToType(data['networkInterfaceNo'], 'String');
      }
      if (data.hasOwnProperty('networkInterfaceName')) {
        obj['networkInterfaceName'] = ApiClient.convertToType(data['networkInterfaceName'], 'String');
      }
      if (data.hasOwnProperty('networkInterfaceIp')) {
        obj['networkInterfaceIp'] = ApiClient.convertToType(data['networkInterfaceIp'], 'String');
      }
      if (data.hasOwnProperty('networkInterfaceDescription')) {
        obj['networkInterfaceDescription'] = ApiClient.convertToType(data['networkInterfaceDescription'], 'String');
      }
      if (data.hasOwnProperty('serverInstanceNo')) {
        obj['serverInstanceNo'] = ApiClient.convertToType(data['serverInstanceNo'], 'String');
      }
      if (data.hasOwnProperty('statusCode')) {
        obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'String');
      }
      if (data.hasOwnProperty('region')) {
        obj['region'] = Region.constructFromObject(data['region']);
      }
      if (data.hasOwnProperty('zone')) {
        obj['zone'] = Zone.constructFromObject(data['zone']);
      }
    }
    return obj;
  }

  /**
   * Network Interface번호
   * @member {String} networkInterfaceNo
   */
  exports.prototype['networkInterfaceNo'] = undefined;
  /**
   * Network Interface이름
   * @member {String} networkInterfaceName
   */
  exports.prototype['networkInterfaceName'] = undefined;
  /**
   * Network Interface IP
   * @member {String} networkInterfaceIp
   */
  exports.prototype['networkInterfaceIp'] = undefined;
  /**
   * Network Interface 설명
   * @member {String} networkInterfaceDescription
   */
  exports.prototype['networkInterfaceDescription'] = undefined;
  /**
   * 서버인스턴스번호
   * @member {String} serverInstanceNo
   */
  exports.prototype['serverInstanceNo'] = undefined;
  /**
   * 상태코드
   * @member {String} statusCode
   */
  exports.prototype['statusCode'] = undefined;
  /**
   * 리전
   * @member {module:model/Region} region
   */
  exports.prototype['region'] = undefined;
  /**
   * ZONE
   * @member {module:model/Zone} zone
   */
  exports.prototype['zone'] = undefined;



  return exports;
}));


