/*
* clouddb
* Cloud DB<br/>https://ncloud.apigw.ntruss.com/clouddb/v2
*
* OpenAPI spec version: 2018-07-02T10:10:19Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Clouddb) {
      root.Clouddb = {};
    }
    root.Clouddb.GetCloudDBImageProductListRequest = factory(root.Clouddb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetCloudDBImageProductListRequest model module.
   * @module model/GetCloudDBImageProductListRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetCloudDBImageProductListRequest</code>.
   * @alias module:model/GetCloudDBImageProductListRequest
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>GetCloudDBImageProductListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCloudDBImageProductListRequest} obj Optional instance to populate.
   * @return {module:model/GetCloudDBImageProductListRequest} The populated <code>GetCloudDBImageProductListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('exclusionProductCode')) {
        obj['exclusionProductCode'] = ApiClient.convertToType(data['exclusionProductCode'], 'String');
      }
      if (data.hasOwnProperty('productCode')) {
        obj['productCode'] = ApiClient.convertToType(data['productCode'], 'String');
      }
      if (data.hasOwnProperty('dbKindCode')) {
        obj['dbKindCode'] = ApiClient.convertToType(data['dbKindCode'], 'String');
      }
      if (data.hasOwnProperty('regionNo')) {
        obj['regionNo'] = ApiClient.convertToType(data['regionNo'], 'String');
      }
    }
    return obj;
  }

  /**
   * 제외할상품코드
   * @member {String} exclusionProductCode
   */
  exports.prototype['exclusionProductCode'] = undefined;
  /**
   * 조회할상품코드
   * @member {String} productCode
   */
  exports.prototype['productCode'] = undefined;
  /**
   * DB유형코드
   * @member {String} dbKindCode
   */
  exports.prototype['dbKindCode'] = undefined;
  /**
   * 리전번호
   * @member {String} regionNo
   */
  exports.prototype['regionNo'] = undefined;



  return exports;
}));


