/*
* clouddb
* Cloud DB<br/>https://ncloud.apigw.ntruss.com/clouddb/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Clouddb) {
      root.Clouddb = {};
    }
    root.Clouddb.SetObjectStorageInfoRequest = factory(root.Clouddb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SetObjectStorageInfoRequest model module.
   * @module model/SetObjectStorageInfoRequest
   * @version 1.4.1
   */

  /**
   * Constructs a new <code>SetObjectStorageInfoRequest</code>.
   * @alias module:model/SetObjectStorageInfoRequest
   * @class
   * @param objectStorageAccessKey {String} 오브젝트스토리지 AccessKey
   * @param objectStorageSecretKey {String} 오브젝트스토리지 SecretKey
   * @param endpoint {String} 엔드포인트
   * @param bucketName {String} 버킷이름
   */
  var exports = function(objectStorageAccessKey, objectStorageSecretKey, endpoint, bucketName) {
    var _this = this;

    _this['objectStorageAccessKey'] = objectStorageAccessKey;
    _this['objectStorageSecretKey'] = objectStorageSecretKey;
    _this['endpoint'] = endpoint;
    _this['bucketName'] = bucketName;
  };

  /**
   * Constructs a <code>SetObjectStorageInfoRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SetObjectStorageInfoRequest} obj Optional instance to populate.
   * @return {module:model/SetObjectStorageInfoRequest} The populated <code>SetObjectStorageInfoRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('objectStorageAccessKey')) {
        obj['objectStorageAccessKey'] = ApiClient.convertToType(data['objectStorageAccessKey'], 'String');
      }
      if (data.hasOwnProperty('objectStorageSecretKey')) {
        obj['objectStorageSecretKey'] = ApiClient.convertToType(data['objectStorageSecretKey'], 'String');
      }
      if (data.hasOwnProperty('endpoint')) {
        obj['endpoint'] = ApiClient.convertToType(data['endpoint'], 'String');
      }
      if (data.hasOwnProperty('bucketName')) {
        obj['bucketName'] = ApiClient.convertToType(data['bucketName'], 'String');
      }
    }
    return obj;
  }

  /**
   * 오브젝트스토리지 AccessKey
   * @member {String} objectStorageAccessKey
   */
  exports.prototype['objectStorageAccessKey'] = undefined;
  /**
   * 오브젝트스토리지 SecretKey
   * @member {String} objectStorageSecretKey
   */
  exports.prototype['objectStorageSecretKey'] = undefined;
  /**
   * 엔드포인트
   * @member {String} endpoint
   */
  exports.prototype['endpoint'] = undefined;
  /**
   * 버킷이름
   * @member {String} bucketName
   */
  exports.prototype['bucketName'] = undefined;



  return exports;
}));


