/*
* vnas
* VPC NAS 관련 API<br/>https://ncloud.apigw.ntruss.com/vnas/v2
*
* OpenAPI spec version: 2020-09-17T02:28:41Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Vnas) {
      root.Vnas = {};
    }
    root.Vnas.SetNasVolumeAccessControlRequest = factory(root.Vnas.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SetNasVolumeAccessControlRequest model module.
   * @module model/SetNasVolumeAccessControlRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SetNasVolumeAccessControlRequest</code>.
   * @alias module:model/SetNasVolumeAccessControlRequest
   * @class
   * @param nasVolumeInstanceNo {String} NAS볼륨인스턴스번호
   */
  var exports = function(nasVolumeInstanceNo) {
    var _this = this;


    _this['nasVolumeInstanceNo'] = nasVolumeInstanceNo;

  };

  /**
   * Constructs a <code>SetNasVolumeAccessControlRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SetNasVolumeAccessControlRequest} obj Optional instance to populate.
   * @return {module:model/SetNasVolumeAccessControlRequest} The populated <code>SetNasVolumeAccessControlRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('nasVolumeInstanceNo')) {
        obj['nasVolumeInstanceNo'] = ApiClient.convertToType(data['nasVolumeInstanceNo'], 'String');
      }
      if (data.hasOwnProperty('serverInstanceNoList')) {
        obj['serverInstanceNoList'] = ApiClient.convertToType(data['serverInstanceNoList'], ['String']);
      }
    }
    return obj;
  }

  /**
   * REGION코드
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * NAS볼륨인스턴스번호
   * @member {String} nasVolumeInstanceNo
   */
  exports.prototype['nasVolumeInstanceNo'] = undefined;
  /**
   * 서버인스턴스번호리스트
   * @member {Array.<String>} serverInstanceNoList
   */
  exports.prototype['serverInstanceNoList'] = undefined;



  return exports;
}));


