/*
* clouddb
* Cloud DB<br/>https://ncloud.beta-apigw.ntruss.com/clouddb/v2
*
* OpenAPI spec version: 2018-06-20T07:19:59Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.ncloud.clouddb.model/AccessControlGroup', 'com.ncloud.clouddb.model/CloudDBConfig', 'com.ncloud.clouddb.model/CloudDBConfigGroup', 'com.ncloud.clouddb.model/CloudDBServerInstance', 'com.ncloud.clouddb.model/CommonCode', 'com.ncloud.clouddb.model/Region', 'com.ncloud.clouddb.model/Zone'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccessControlGroup'), require('./CloudDBConfig'), require('./CloudDBConfigGroup'), require('./CloudDBServerInstance'), require('./CommonCode'), require('./Region'), require('./Zone'));
  } else {
    // Browser globals (root is window)
    if (!root.Clouddb) {
      root.Clouddb = {};
    }
    root.Clouddb.CloudDBInstance = factory(root.Clouddb.ApiClient, root.Clouddb.AccessControlGroup, root.Clouddb.CloudDBConfig, root.Clouddb.CloudDBConfigGroup, root.Clouddb.CloudDBServerInstance, root.Clouddb.CommonCode, root.Clouddb.Region, root.Clouddb.Zone);
  }
}(this, function(ApiClient, AccessControlGroup, CloudDBConfig, CloudDBConfigGroup, CloudDBServerInstance, CommonCode, Region, Zone) {
  'use strict';




  /**
   * The CloudDBInstance model module.
   * @module com.ncloud.clouddb.model/CloudDBInstance
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CloudDBInstance</code>.
   * @alias module:com.ncloud.clouddb.model/CloudDBInstance
   * @class
   */
  var exports = function() {
    var _this = this;



























  };

  /**
   * Constructs a <code>CloudDBInstance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.clouddb.model/CloudDBInstance} obj Optional instance to populate.
   * @return {module:com.ncloud.clouddb.model/CloudDBInstance} The populated <code>CloudDBInstance</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('cloudDBInstanceNo')) {
        obj['cloudDBInstanceNo'] = ApiClient.convertToType(data['cloudDBInstanceNo'], 'String');
      }
      if (data.hasOwnProperty('cloudDBServiceName')) {
        obj['cloudDBServiceName'] = ApiClient.convertToType(data['cloudDBServiceName'], 'String');
      }
      if (data.hasOwnProperty('dbKindCode')) {
        obj['dbKindCode'] = ApiClient.convertToType(data['dbKindCode'], 'String');
      }
      if (data.hasOwnProperty('engineVersion')) {
        obj['engineVersion'] = ApiClient.convertToType(data['engineVersion'], 'String');
      }
      if (data.hasOwnProperty('cpuCount')) {
        obj['cpuCount'] = ApiClient.convertToType(data['cpuCount'], 'Number');
      }
      if (data.hasOwnProperty('memorySize')) {
        obj['memorySize'] = ApiClient.convertToType(data['memorySize'], 'Number');
      }
      if (data.hasOwnProperty('dataStorageType')) {
        obj['dataStorageType'] = CommonCode.constructFromObject(data['dataStorageType']);
      }
      if (data.hasOwnProperty('licenseCode')) {
        obj['licenseCode'] = ApiClient.convertToType(data['licenseCode'], 'String');
      }
      if (data.hasOwnProperty('cloudDBPort')) {
        obj['cloudDBPort'] = ApiClient.convertToType(data['cloudDBPort'], 'Number');
      }
      if (data.hasOwnProperty('isHa')) {
        obj['isHa'] = ApiClient.convertToType(data['isHa'], 'Boolean');
      }
      if (data.hasOwnProperty('backupTime')) {
        obj['backupTime'] = ApiClient.convertToType(data['backupTime'], 'String');
      }
      if (data.hasOwnProperty('backupFileRetentionPeriod')) {
        obj['backupFileRetentionPeriod'] = ApiClient.convertToType(data['backupFileRetentionPeriod'], 'Number');
      }
      if (data.hasOwnProperty('cloudDBInstanceStatusName')) {
        obj['cloudDBInstanceStatusName'] = ApiClient.convertToType(data['cloudDBInstanceStatusName'], 'String');
      }
      if (data.hasOwnProperty('collation')) {
        obj['collation'] = ApiClient.convertToType(data['collation'], 'String');
      }
      if (data.hasOwnProperty('rebootScheduleTime')) {
        obj['rebootScheduleTime'] = ApiClient.convertToType(data['rebootScheduleTime'], 'String');
      }
      if (data.hasOwnProperty('createDate')) {
        obj['createDate'] = ApiClient.convertToType(data['createDate'], 'String');
      }
      if (data.hasOwnProperty('cloudDBImageProductCode')) {
        obj['cloudDBImageProductCode'] = ApiClient.convertToType(data['cloudDBImageProductCode'], 'String');
      }
      if (data.hasOwnProperty('cloudDBProductCode')) {
        obj['cloudDBProductCode'] = ApiClient.convertToType(data['cloudDBProductCode'], 'String');
      }
      if (data.hasOwnProperty('isCloudDBConfigNeedReboot')) {
        obj['isCloudDBConfigNeedReboot'] = ApiClient.convertToType(data['isCloudDBConfigNeedReboot'], 'Boolean');
      }
      if (data.hasOwnProperty('isCloudDBNeedReboot')) {
        obj['isCloudDBNeedReboot'] = ApiClient.convertToType(data['isCloudDBNeedReboot'], 'Boolean');
      }
      if (data.hasOwnProperty('zone')) {
        obj['zone'] = Zone.constructFromObject(data['zone']);
      }
      if (data.hasOwnProperty('region')) {
        obj['region'] = Region.constructFromObject(data['region']);
      }
      if (data.hasOwnProperty('cloudDBConfigList')) {
        obj['cloudDBConfigList'] = ApiClient.convertToType(data['cloudDBConfigList'], [CloudDBConfig]);
      }
      if (data.hasOwnProperty('cloudDBConfigGroupList')) {
        obj['cloudDBConfigGroupList'] = ApiClient.convertToType(data['cloudDBConfigGroupList'], [CloudDBConfigGroup]);
      }
      if (data.hasOwnProperty('accessControlGroupList')) {
        obj['accessControlGroupList'] = ApiClient.convertToType(data['accessControlGroupList'], [AccessControlGroup]);
      }
      if (data.hasOwnProperty('cloudDBServerInstanceList')) {
        obj['cloudDBServerInstanceList'] = ApiClient.convertToType(data['cloudDBServerInstanceList'], [CloudDBServerInstance]);
      }
    }
    return obj;
  }

  /**
   * CloudDB인스턴스번호
   * @member {String} cloudDBInstanceNo
   */
  exports.prototype['cloudDBInstanceNo'] = undefined;
  /**
   * CloudDB서비스이름
   * @member {String} cloudDBServiceName
   */
  exports.prototype['cloudDBServiceName'] = undefined;
  /**
   * DB유형코드
   * @member {String} dbKindCode
   */
  exports.prototype['dbKindCode'] = undefined;
  /**
   * 엔진버전
   * @member {String} engineVersion
   */
  exports.prototype['engineVersion'] = undefined;
  /**
   * CPU개수
   * @member {Number} cpuCount
   */
  exports.prototype['cpuCount'] = undefined;
  /**
   * 메모리사이즈
   * @member {Number} memorySize
   */
  exports.prototype['memorySize'] = undefined;
  /**
   * 데이터스토리지타입
   * @member {module:com.ncloud.clouddb.model/CommonCode} dataStorageType
   */
  exports.prototype['dataStorageType'] = undefined;
  /**
   * 라이센스코드
   * @member {String} licenseCode
   */
  exports.prototype['licenseCode'] = undefined;
  /**
   * CloudDB포트
   * @member {Number} cloudDBPort
   */
  exports.prototype['cloudDBPort'] = undefined;
  /**
   * HA여부
   * @member {Boolean} isHa
   */
  exports.prototype['isHa'] = undefined;
  /**
   * 백업시간
   * @member {String} backupTime
   */
  exports.prototype['backupTime'] = undefined;
  /**
   * 백업파일유지기간
   * @member {Number} backupFileRetentionPeriod
   */
  exports.prototype['backupFileRetentionPeriod'] = undefined;
  /**
   * CloudDB인스턴스상태이름
   * @member {String} cloudDBInstanceStatusName
   */
  exports.prototype['cloudDBInstanceStatusName'] = undefined;
  /**
   * Collation
   * @member {String} collation
   */
  exports.prototype['collation'] = undefined;
  /**
   * 재부팅예약시간
   * @member {String} rebootScheduleTime
   */
  exports.prototype['rebootScheduleTime'] = undefined;
  /**
   * 생성일시
   * @member {String} createDate
   */
  exports.prototype['createDate'] = undefined;
  /**
   * CloudDB이미지상품코드
   * @member {String} cloudDBImageProductCode
   */
  exports.prototype['cloudDBImageProductCode'] = undefined;
  /**
   * CloudDB상품코드
   * @member {String} cloudDBProductCode
   */
  exports.prototype['cloudDBProductCode'] = undefined;
  /**
   * CloudDB설정재부팅필요여부
   * @member {Boolean} isCloudDBConfigNeedReboot
   */
  exports.prototype['isCloudDBConfigNeedReboot'] = undefined;
  /**
   * CloudDB재부팅필요여부
   * @member {Boolean} isCloudDBNeedReboot
   */
  exports.prototype['isCloudDBNeedReboot'] = undefined;
  /**
   * Zone
   * @member {module:com.ncloud.clouddb.model/Zone} zone
   */
  exports.prototype['zone'] = undefined;
  /**
   * 리전
   * @member {module:com.ncloud.clouddb.model/Region} region
   */
  exports.prototype['region'] = undefined;
  /**
   * @member {Array.<module:com.ncloud.clouddb.model/CloudDBConfig>} cloudDBConfigList
   */
  exports.prototype['cloudDBConfigList'] = undefined;
  /**
   * @member {Array.<module:com.ncloud.clouddb.model/CloudDBConfigGroup>} cloudDBConfigGroupList
   */
  exports.prototype['cloudDBConfigGroupList'] = undefined;
  /**
   * @member {Array.<module:com.ncloud.clouddb.model/AccessControlGroup>} accessControlGroupList
   */
  exports.prototype['accessControlGroupList'] = undefined;
  /**
   * @member {Array.<module:com.ncloud.clouddb.model/CloudDBServerInstance>} cloudDBServerInstanceList
   */
  exports.prototype['cloudDBServerInstanceList'] = undefined;



  return exports;
}));


