/*
* clouddb
* Cloud DB<br/>https://ncloud.beta-apigw.ntruss.com/clouddb/v2
*
* OpenAPI spec version: 2018-06-20T07:19:59Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Clouddb) {
      root.Clouddb = {};
    }
    root.Clouddb.CloudDBConfig = factory(root.Clouddb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CloudDBConfig model module.
   * @module com.ncloud.clouddb.model/CloudDBConfig
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CloudDBConfig</code>.
   * @alias module:com.ncloud.clouddb.model/CloudDBConfig
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CloudDBConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.clouddb.model/CloudDBConfig} obj Optional instance to populate.
   * @return {module:com.ncloud.clouddb.model/CloudDBConfig} The populated <code>CloudDBConfig</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('configName')) {
        obj['configName'] = ApiClient.convertToType(data['configName'], 'String');
      }
      if (data.hasOwnProperty('configValue')) {
        obj['configValue'] = ApiClient.convertToType(data['configValue'], 'String');
      }
    }
    return obj;
  }

  /**
   * 설정명
   * @member {String} configName
   */
  exports.prototype['configName'] = undefined;
  /**
   * 설정값
   * @member {String} configValue
   */
  exports.prototype['configValue'] = undefined;



  return exports;
}));


