/*
* clouddb
* Cloud DB<br/>https://ncloud.apigw.ntruss.com/clouddb/v2
*
* OpenAPI spec version: 2018-06-21T02:28:05Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Clouddb) {
      root.Clouddb = {};
    }
    root.Clouddb.CommonCode = factory(root.Clouddb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CommonCode model module.
   * @module com.ncloud.clouddb.model/CommonCode
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CommonCode</code>.
   * @alias module:com.ncloud.clouddb.model/CommonCode
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CommonCode</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.clouddb.model/CommonCode} obj Optional instance to populate.
   * @return {module:com.ncloud.clouddb.model/CommonCode} The populated <code>CommonCode</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('codeName')) {
        obj['codeName'] = ApiClient.convertToType(data['codeName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} code
   */
  exports.prototype['code'] = undefined;
  /**
   * @member {String} codeName
   */
  exports.prototype['codeName'] = undefined;



  return exports;
}));


