/*
* loadbalancer
* <br/>https://ncloud.apigw.ntruss.com/loadbalancer/v2
*
* OpenAPI spec version: 2018-06-21T02:19:18Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Loadbalancer) {
      root.Loadbalancer = {};
    }
    root.Loadbalancer.DeleteLoadBalancerInstancesRequest = factory(root.Loadbalancer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeleteLoadBalancerInstancesRequest model module.
   * @module model/DeleteLoadBalancerInstancesRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DeleteLoadBalancerInstancesRequest</code>.
   * @alias module:model/DeleteLoadBalancerInstancesRequest
   * @class
   * @param loadBalancerInstanceNoList {Array.<String>} 로드밸런서인스턴스번호리스트
   */
  var exports = function(loadBalancerInstanceNoList) {
    var _this = this;

    _this['loadBalancerInstanceNoList'] = loadBalancerInstanceNoList;
  };

  /**
   * Constructs a <code>DeleteLoadBalancerInstancesRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeleteLoadBalancerInstancesRequest} obj Optional instance to populate.
   * @return {module:model/DeleteLoadBalancerInstancesRequest} The populated <code>DeleteLoadBalancerInstancesRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('loadBalancerInstanceNoList')) {
        obj['loadBalancerInstanceNoList'] = ApiClient.convertToType(data['loadBalancerInstanceNoList'], ['String']);
      }
    }
    return obj;
  }

  /**
   * 로드밸런서인스턴스번호리스트
   * @member {Array.<String>} loadBalancerInstanceNoList
   */
  exports.prototype['loadBalancerInstanceNoList'] = undefined;



  return exports;
}));


