/*
* autoscaling
* <br/>https://ncloud.beta-apigw.ntruss.com/autoscaling/v2
*
* OpenAPI spec version: 2018-06-20T07:13:45Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.ncloud.autoscaling.model/CommonCode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CommonCode'));
  } else {
    // Browser globals (root is window)
    if (!root.Autoscaling) {
      root.Autoscaling = {};
    }
    root.Autoscaling.SuspendedProcess = factory(root.Autoscaling.ApiClient, root.Autoscaling.CommonCode);
  }
}(this, function(ApiClient, CommonCode) {
  'use strict';




  /**
   * The SuspendedProcess model module.
   * @module com.ncloud.autoscaling.model/SuspendedProcess
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SuspendedProcess</code>.
   * @alias module:com.ncloud.autoscaling.model/SuspendedProcess
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SuspendedProcess</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.autoscaling.model/SuspendedProcess} obj Optional instance to populate.
   * @return {module:com.ncloud.autoscaling.model/SuspendedProcess} The populated <code>SuspendedProcess</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('process')) {
        obj['process'] = CommonCode.constructFromObject(data['process']);
      }
      if (data.hasOwnProperty('suspensionReason')) {
        obj['suspensionReason'] = ApiClient.convertToType(data['suspensionReason'], 'String');
      }
    }
    return obj;
  }

  /**
   * 프로세스
   * @member {module:com.ncloud.autoscaling.model/CommonCode} process
   */
  exports.prototype['process'] = undefined;
  /**
   * 프로세스보류원인
   * @member {String} suspensionReason
   */
  exports.prototype['suspensionReason'] = undefined;



  return exports;
}));


