/*
* monitoring
* <br/>https://ncloud.beta-apigw.ntruss.com/monitoring/v2
*
* OpenAPI spec version: 2018-06-20T07:15:55Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.ncloud.monitoring.model/DataPoint'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DataPoint'));
  } else {
    // Browser globals (root is window)
    if (!root.Monitoring) {
      root.Monitoring = {};
    }
    root.Monitoring.DataPoints = factory(root.Monitoring.ApiClient, root.Monitoring.DataPoint);
  }
}(this, function(ApiClient, DataPoint) {
  'use strict';




  /**
   * The DataPoints model module.
   * @module com.ncloud.monitoring.model/DataPoints
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DataPoints</code>.
   * @alias module:com.ncloud.monitoring.model/DataPoints
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>DataPoints</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.monitoring.model/DataPoints} obj Optional instance to populate.
   * @return {module:com.ncloud.monitoring.model/DataPoints} The populated <code>DataPoints</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('average')) {
        obj['average'] = ApiClient.convertToType(data['average'], 'Number');
      }
      if (data.hasOwnProperty('maximum')) {
        obj['maximum'] = ApiClient.convertToType(data['maximum'], 'Number');
      }
      if (data.hasOwnProperty('minimum')) {
        obj['minimum'] = ApiClient.convertToType(data['minimum'], 'Number');
      }
      if (data.hasOwnProperty('sum')) {
        obj['sum'] = ApiClient.convertToType(data['sum'], 'Number');
      }
      if (data.hasOwnProperty('dataPointList')) {
        obj['dataPointList'] = ApiClient.convertToType(data['dataPointList'], [DataPoint]);
      }
    }
    return obj;
  }

  /**
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * @member {Number} average
   */
  exports.prototype['average'] = undefined;
  /**
   * @member {Number} maximum
   */
  exports.prototype['maximum'] = undefined;
  /**
   * @member {Number} minimum
   */
  exports.prototype['minimum'] = undefined;
  /**
   * @member {Number} sum
   */
  exports.prototype['sum'] = undefined;
  /**
   * @member {Array.<module:com.ncloud.monitoring.model/DataPoint>} dataPointList
   */
  exports.prototype['dataPointList'] = undefined;



  return exports;
}));


