/*
* monitoring
* <br/>https://ncloud.apigw.ntruss.com/monitoring/v2
*
* OpenAPI spec version: 2018-06-21T02:23:11Z
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Monitoring) {
      root.Monitoring = {};
    }
    root.Monitoring.Metric = factory(root.Monitoring.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Metric model module.
   * @module com.ncloud.monitoring.model/Metric
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Metric</code>.
   * @alias module:com.ncloud.monitoring.model/Metric
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Metric</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ncloud.monitoring.model/Metric} obj Optional instance to populate.
   * @return {module:com.ncloud.monitoring.model/Metric} The populated <code>Metric</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('instanceNo')) {
        obj['instanceNo'] = ApiClient.convertToType(data['instanceNo'], 'String');
      }
      if (data.hasOwnProperty('metricName')) {
        obj['metricName'] = ApiClient.convertToType(data['metricName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} instanceNo
   */
  exports.prototype['instanceNo'] = undefined;
  /**
   * @member {String} metricName
   */
  exports.prototype['metricName'] = undefined;



  return exports;
}));


