/*
* vserver
* VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
*
* NBP corp.
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    factory(require('expect.js'), require('../../src/index'));
  } else {
    factory(root.expect, root.Vserver);
  }
}(this, function(expect, Vserver) {
  'use strict';

  var client = new Vserver.ApiClient({
    accessKey: 'your access key',
    secretKey: 'your secret key'
  });
  var instance = new Vserver.V2Api(client);

  describe('V2Api', function() {
    describe('addAccessControlGroupInboundRule', function() {
      it('should call addAccessControlGroupInboundRule successfully', function(done) {
        //uncomment below and update the code to test addAccessControlGroupInboundRule
        //instance.addAccessControlGroupInboundRule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('addAccessControlGroupOutboundRule', function() {
      it('should call addAccessControlGroupOutboundRule successfully', function(done) {
        //uncomment below and update the code to test addAccessControlGroupOutboundRule
        //instance.addAccessControlGroupOutboundRule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('addNetworkInterfaceAccessControlGroup', function() {
      it('should call addNetworkInterfaceAccessControlGroup successfully', function(done) {
        //uncomment below and update the code to test addNetworkInterfaceAccessControlGroup
        //instance.addNetworkInterfaceAccessControlGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('addPlacementGroupServerInstance', function() {
      it('should call addPlacementGroupServerInstance successfully', function(done) {
        //uncomment below and update the code to test addPlacementGroupServerInstance
        //instance.addPlacementGroupServerInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('associatePublicIpWithServerInstance', function() {
      it('should call associatePublicIpWithServerInstance successfully', function(done) {
        //uncomment below and update the code to test associatePublicIpWithServerInstance
        //instance.associatePublicIpWithServerInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('attachBlockStorageInstance', function() {
      it('should call attachBlockStorageInstance successfully', function(done) {
        //uncomment below and update the code to test attachBlockStorageInstance
        //instance.attachBlockStorageInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('attachNetworkInterface', function() {
      it('should call attachNetworkInterface successfully', function(done) {
        //uncomment below and update the code to test attachNetworkInterface
        //instance.attachNetworkInterface(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('changeBlockStorageVolumeSize', function() {
      it('should call changeBlockStorageVolumeSize successfully', function(done) {
        //uncomment below and update the code to test changeBlockStorageVolumeSize
        //instance.changeBlockStorageVolumeSize(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('changeServerInstanceSpec', function() {
      it('should call changeServerInstanceSpec successfully', function(done) {
        //uncomment below and update the code to test changeServerInstanceSpec
        //instance.changeServerInstanceSpec(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createAccessControlGroup', function() {
      it('should call createAccessControlGroup successfully', function(done) {
        //uncomment below and update the code to test createAccessControlGroup
        //instance.createAccessControlGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createBlockStorageInstance', function() {
      it('should call createBlockStorageInstance successfully', function(done) {
        //uncomment below and update the code to test createBlockStorageInstance
        //instance.createBlockStorageInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createBlockStorageSnapshotInstance', function() {
      it('should call createBlockStorageSnapshotInstance successfully', function(done) {
        //uncomment below and update the code to test createBlockStorageSnapshotInstance
        //instance.createBlockStorageSnapshotInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createInitScript', function() {
      it('should call createInitScript successfully', function(done) {
        //uncomment below and update the code to test createInitScript
        //instance.createInitScript(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createLoginKey', function() {
      it('should call createLoginKey successfully', function(done) {
        //uncomment below and update the code to test createLoginKey
        //instance.createLoginKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createMemberServerImageInstance', function() {
      it('should call createMemberServerImageInstance successfully', function(done) {
        //uncomment below and update the code to test createMemberServerImageInstance
        //instance.createMemberServerImageInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createNetworkInterface', function() {
      it('should call createNetworkInterface successfully', function(done) {
        //uncomment below and update the code to test createNetworkInterface
        //instance.createNetworkInterface(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createPlacementGroup', function() {
      it('should call createPlacementGroup successfully', function(done) {
        //uncomment below and update the code to test createPlacementGroup
        //instance.createPlacementGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createPublicIpInstance', function() {
      it('should call createPublicIpInstance successfully', function(done) {
        //uncomment below and update the code to test createPublicIpInstance
        //instance.createPublicIpInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('createServerInstances', function() {
      it('should call createServerInstances successfully', function(done) {
        //uncomment below and update the code to test createServerInstances
        //instance.createServerInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteAccessControlGroup', function() {
      it('should call deleteAccessControlGroup successfully', function(done) {
        //uncomment below and update the code to test deleteAccessControlGroup
        //instance.deleteAccessControlGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteBlockStorageInstances', function() {
      it('should call deleteBlockStorageInstances successfully', function(done) {
        //uncomment below and update the code to test deleteBlockStorageInstances
        //instance.deleteBlockStorageInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteBlockStorageSnapshotInstances', function() {
      it('should call deleteBlockStorageSnapshotInstances successfully', function(done) {
        //uncomment below and update the code to test deleteBlockStorageSnapshotInstances
        //instance.deleteBlockStorageSnapshotInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteInitScripts', function() {
      it('should call deleteInitScripts successfully', function(done) {
        //uncomment below and update the code to test deleteInitScripts
        //instance.deleteInitScripts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteLoginKeys', function() {
      it('should call deleteLoginKeys successfully', function(done) {
        //uncomment below and update the code to test deleteLoginKeys
        //instance.deleteLoginKeys(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteMemberServerImageInstances', function() {
      it('should call deleteMemberServerImageInstances successfully', function(done) {
        //uncomment below and update the code to test deleteMemberServerImageInstances
        //instance.deleteMemberServerImageInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deleteNetworkInterface', function() {
      it('should call deleteNetworkInterface successfully', function(done) {
        //uncomment below and update the code to test deleteNetworkInterface
        //instance.deleteNetworkInterface(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deletePlacementGroup', function() {
      it('should call deletePlacementGroup successfully', function(done) {
        //uncomment below and update the code to test deletePlacementGroup
        //instance.deletePlacementGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('deletePublicIpInstance', function() {
      it('should call deletePublicIpInstance successfully', function(done) {
        //uncomment below and update the code to test deletePublicIpInstance
        //instance.deletePublicIpInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('detachBlockStorageInstances', function() {
      it('should call detachBlockStorageInstances successfully', function(done) {
        //uncomment below and update the code to test detachBlockStorageInstances
        //instance.detachBlockStorageInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('detachNetworkInterface', function() {
      it('should call detachNetworkInterface successfully', function(done) {
        //uncomment below and update the code to test detachNetworkInterface
        //instance.detachNetworkInterface(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('disassociatePublicIpFromServerInstance', function() {
      it('should call disassociatePublicIpFromServerInstance successfully', function(done) {
        //uncomment below and update the code to test disassociatePublicIpFromServerInstance
        //instance.disassociatePublicIpFromServerInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getAccessControlGroupDetail', function() {
      it('should call getAccessControlGroupDetail successfully', function(done) {
        //uncomment below and update the code to test getAccessControlGroupDetail
        //instance.getAccessControlGroupDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getAccessControlGroupList', function() {
      it('should call getAccessControlGroupList successfully', function(done) {
        //uncomment below and update the code to test getAccessControlGroupList
        //instance.getAccessControlGroupList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getAccessControlGroupRuleList', function() {
      it('should call getAccessControlGroupRuleList successfully', function(done) {
        //uncomment below and update the code to test getAccessControlGroupRuleList
        //instance.getAccessControlGroupRuleList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getBlockStorageInstanceDetail', function() {
      it('should call getBlockStorageInstanceDetail successfully', function(done) {
        //uncomment below and update the code to test getBlockStorageInstanceDetail
        //instance.getBlockStorageInstanceDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getBlockStorageInstanceList', function() {
      it('should call getBlockStorageInstanceList successfully', function(done) {
        //uncomment below and update the code to test getBlockStorageInstanceList
        //instance.getBlockStorageInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getBlockStorageSnapshotInstanceDetail', function() {
      it('should call getBlockStorageSnapshotInstanceDetail successfully', function(done) {
        //uncomment below and update the code to test getBlockStorageSnapshotInstanceDetail
        //instance.getBlockStorageSnapshotInstanceDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getBlockStorageSnapshotInstanceList', function() {
      it('should call getBlockStorageSnapshotInstanceList successfully', function(done) {
        //uncomment below and update the code to test getBlockStorageSnapshotInstanceList
        //instance.getBlockStorageSnapshotInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getInitScriptDetail', function() {
      it('should call getInitScriptDetail successfully', function(done) {
        //uncomment below and update the code to test getInitScriptDetail
        //instance.getInitScriptDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getInitScriptList', function() {
      it('should call getInitScriptList successfully', function(done) {
        //uncomment below and update the code to test getInitScriptList
        //instance.getInitScriptList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getLoginKeyList', function() {
      it('should call getLoginKeyList successfully', function(done) {
        //uncomment below and update the code to test getLoginKeyList
        //instance.getLoginKeyList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getMemberServerImageInstanceDetail', function() {
      it('should call getMemberServerImageInstanceDetail successfully', function(done) {
        //uncomment below and update the code to test getMemberServerImageInstanceDetail
        //instance.getMemberServerImageInstanceDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getMemberServerImageInstanceList', function() {
      it('should call getMemberServerImageInstanceList successfully', function(done) {
        //uncomment below and update the code to test getMemberServerImageInstanceList
        //instance.getMemberServerImageInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getNetworkInterfaceDetail', function() {
      it('should call getNetworkInterfaceDetail successfully', function(done) {
        //uncomment below and update the code to test getNetworkInterfaceDetail
        //instance.getNetworkInterfaceDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getNetworkInterfaceList', function() {
      it('should call getNetworkInterfaceList successfully', function(done) {
        //uncomment below and update the code to test getNetworkInterfaceList
        //instance.getNetworkInterfaceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getPlacementGroupDetail', function() {
      it('should call getPlacementGroupDetail successfully', function(done) {
        //uncomment below and update the code to test getPlacementGroupDetail
        //instance.getPlacementGroupDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getPlacementGroupList', function() {
      it('should call getPlacementGroupList successfully', function(done) {
        //uncomment below and update the code to test getPlacementGroupList
        //instance.getPlacementGroupList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getPublicIpInstanceDetail', function() {
      it('should call getPublicIpInstanceDetail successfully', function(done) {
        //uncomment below and update the code to test getPublicIpInstanceDetail
        //instance.getPublicIpInstanceDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getPublicIpInstanceList', function() {
      it('should call getPublicIpInstanceList successfully', function(done) {
        //uncomment below and update the code to test getPublicIpInstanceList
        //instance.getPublicIpInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getPublicIpTargetServerInstanceList', function() {
      it('should call getPublicIpTargetServerInstanceList successfully', function(done) {
        //uncomment below and update the code to test getPublicIpTargetServerInstanceList
        //instance.getPublicIpTargetServerInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getRegionList', function() {
      it('should call getRegionList successfully', function(done) {
        //uncomment below and update the code to test getRegionList
        //instance.getRegionList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getRootPassword', function() {
      it('should call getRootPassword successfully', function(done) {
        //uncomment below and update the code to test getRootPassword
        //instance.getRootPassword(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getRootPasswordServerInstanceList', function() {
      it('should call getRootPasswordServerInstanceList successfully', function(done) {
        //uncomment below and update the code to test getRootPasswordServerInstanceList
        //instance.getRootPasswordServerInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getServerImageProductList', function() {
      it('should call getServerImageProductList successfully', function(done) {
        //uncomment below and update the code to test getServerImageProductList
        //instance.getServerImageProductList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getServerInstanceDetail', function() {
      it('should call getServerInstanceDetail successfully', function(done) {
        //uncomment below and update the code to test getServerInstanceDetail
        //instance.getServerInstanceDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getServerInstanceList', function() {
      it('should call getServerInstanceList successfully', function(done) {
        //uncomment below and update the code to test getServerInstanceList
        //instance.getServerInstanceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getServerProductList', function() {
      it('should call getServerProductList successfully', function(done) {
        //uncomment below and update the code to test getServerProductList
        //instance.getServerProductList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('getZoneList', function() {
      it('should call getZoneList successfully', function(done) {
        //uncomment below and update the code to test getZoneList
        //instance.getZoneList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('importLoginKey', function() {
      it('should call importLoginKey successfully', function(done) {
        //uncomment below and update the code to test importLoginKey
        //instance.importLoginKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('rebootServerInstances', function() {
      it('should call rebootServerInstances successfully', function(done) {
        //uncomment below and update the code to test rebootServerInstances
        //instance.rebootServerInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('removeAccessControlGroupInboundRule', function() {
      it('should call removeAccessControlGroupInboundRule successfully', function(done) {
        //uncomment below and update the code to test removeAccessControlGroupInboundRule
        //instance.removeAccessControlGroupInboundRule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('removeAccessControlGroupOutboundRule', function() {
      it('should call removeAccessControlGroupOutboundRule successfully', function(done) {
        //uncomment below and update the code to test removeAccessControlGroupOutboundRule
        //instance.removeAccessControlGroupOutboundRule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('removeNetworkInterfaceAccessControlGroup', function() {
      it('should call removeNetworkInterfaceAccessControlGroup successfully', function(done) {
        //uncomment below and update the code to test removeNetworkInterfaceAccessControlGroup
        //instance.removeNetworkInterfaceAccessControlGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('removePlacementGroupServerInstance', function() {
      it('should call removePlacementGroupServerInstance successfully', function(done) {
        //uncomment below and update the code to test removePlacementGroupServerInstance
        //instance.removePlacementGroupServerInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('startServerInstances', function() {
      it('should call startServerInstances successfully', function(done) {
        //uncomment below and update the code to test startServerInstances
        //instance.startServerInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('stopServerInstances', function() {
      it('should call stopServerInstances successfully', function(done) {
        //uncomment below and update the code to test stopServerInstances
        //instance.stopServerInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
    describe('terminateServerInstances', function() {
      it('should call terminateServerInstances successfully', function(done) {
        //uncomment below and update the code to test terminateServerInstances
        //instance.terminateServerInstances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //done();
        //});
        done();
      });
    });
  });

}));
